'use strict';var bh=function(a,b,c){a.timeOfStartCall=(new Date).getTime();var d=c||Ia,e=d.document,f=a.nonce||La(d);f&&!a.nonce&&(a.nonce=f);if("help"==a.flow){var g=Na("document.location.href",d);!a.helpCenterContext&&g&&(a.helpCenterContext=g.substring(0,1200));g=!0;if(b&&JSON&&JSON.stringify){var h=JSON.stringify(b);(g=1200>=h.length)&&(a.psdJson=h)}g||(b={invalidPsd:!0})}b=[a,b,c];d.GOOGLE_FEEDBACK_START_ARGUMENTS=b;c=a.serverUri||"//www.google.com/tools/feedback";if(g=d.GOOGLE_FEEDBACK_START)g.apply(d,b);
else{d=c+"/load.js?";for(var n in a)b=a[n],null==b||Ta(b)||(d+=encodeURIComponent(n)+"="+encodeURIComponent(b)+"&");a=gg(Tf(e),"SCRIPT");f&&a.setAttribute("nonce",f);We(a,ig(d));e.body.appendChild(a)}};v("userfeedback.api.startFeedback",bh);var ch=function(){this.j=this.h=this.u=this.modelName=this.l=this.g=this.hd="";this.C=this.s=this.m=!1};var dh=chrome.i18n.getMessage("4163185390680253103"),eh=chrome.i18n.getMessage("492097680647953484"),fh=chrome.i18n.getMessage("2575016469622936324"),hh=chrome.i18n.getMessage("128276876460319075"),ih=chrome.i18n.getMessage("3326722026796849289"),jh=chrome.i18n.getMessage("1018984561488520517"),kh=chrome.i18n.getMessage("8205999658352447129"),lh=chrome.i18n.getMessage("5723583529370342957"),mh=chrome.i18n.getMessage("1550904064710828958"),nh=chrome.i18n.getMessage("5014364904504073524"),oh=chrome.i18n.getMessage("2194670894476780934"),
ph=chrome.i18n.getMessage("6614468912728530636"),qh=chrome.i18n.getMessage("5910595154486533449"),rh=chrome.i18n.getMessage("5363086287710390513"),sh=chrome.i18n.getMessage("244647017322945605"),th=chrome.i18n.getMessage("5375576275991472719"),uh=chrome.i18n.getMessage("4592127349908255218"),vh=chrome.i18n.getMessage("843316808366399491"),wh=chrome.i18n.getMessage("5699813974548050528"),xh=chrome.i18n.getMessage("8515148417333877999"),yh=chrome.i18n.getMessage("1636686747687494376"),zh=chrome.i18n.getMessage("4148300086676792937"),
Ah=chrome.i18n.getMessage("3219866268410307919"),Bh=chrome.i18n.getMessage("9211708838274008657"),Ch=chrome.i18n.getMessage("8706273405040403641"),Dh=chrome.i18n.getMessage("4756056595565370923"),Eh=chrome.i18n.getMessage("7876724262035435114"),Fh=chrome.i18n.getMessage("5485620192329479690"),Gh=chrome.i18n.getMessage("6963873398546068901"),Hh=chrome.i18n.getMessage("3567591856726172993"),Ih=chrome.i18n.getMessage("3239956785410157548");/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var Jh={"* ARIA-CHECKED":!0,"* ARIA-COLCOUNT":!0,"* ARIA-COLINDEX":!0,"* ARIA-CONTROLS":!0,"* ARIA-DESCRIBEDBY":!0,"* ARIA-DISABLED":!0,"* ARIA-EXPANDED":!0,"* ARIA-GOOG-EDITABLE":!0,"* ARIA-HASPOPUP":!0,"* ARIA-HIDDEN":!0,"* ARIA-LABEL":!0,"* ARIA-LABELLEDBY":!0,"* ARIA-MULTILINE":!0,"* ARIA-MULTISELECTABLE":!0,"* ARIA-ORIENTATION":!0,"* ARIA-PLACEHOLDER":!0,"* ARIA-READONLY":!0,"* ARIA-REQUIRED":!0,"* ARIA-ROLEDESCRIPTION":!0,"* ARIA-ROWCOUNT":!0,"* ARIA-ROWINDEX":!0,"* ARIA-SELECTED":!0,"* ABBR":!0,
"* ACCEPT":!0,"* ACCESSKEY":!0,"* ALIGN":!0,"* ALT":!0,"* AUTOCOMPLETE":!0,"* AXIS":!0,"* BGCOLOR":!0,"* BORDER":!0,"* CELLPADDING":!0,"* CELLSPACING":!0,"* CHAROFF":!0,"* CHAR":!0,"* CHECKED":!0,"* CLEAR":!0,"* COLOR":!0,"* COLSPAN":!0,"* COLS":!0,"* COMPACT":!0,"* COORDS":!0,"* DATETIME":!0,"* DIR":!0,"* DISABLED":!0,"* ENCTYPE":!0,"* FACE":!0,"* FRAME":!0,"* HEIGHT":!0,"* HREFLANG":!0,"* HSPACE":!0,"* ISMAP":!0,"* LABEL":!0,"* LANG":!0,"* MAX":!0,"* MAXLENGTH":!0,"* METHOD":!0,"* MULTIPLE":!0,
"* NOHREF":!0,"* NOSHADE":!0,"* NOWRAP":!0,"* OPEN":!0,"* READONLY":!0,"* REQUIRED":!0,"* REL":!0,"* REV":!0,"* ROLE":!0,"* ROWSPAN":!0,"* ROWS":!0,"* RULES":!0,"* SCOPE":!0,"* SELECTED":!0,"* SHAPE":!0,"* SIZE":!0,"* SPAN":!0,"* START":!0,"* SUMMARY":!0,"* TABINDEX":!0,"* TITLE":!0,"* TYPE":!0,"* VALIGN":!0,"* VALUE":!0,"* VSPACE":!0,"* WIDTH":!0},Kh={"* USEMAP":!0,"* ACTION":!0,"* CITE":!0,"* HREF":!0,"* LONGDESC":!0,"* SRC":!0,"LINK HREF":!0,"* FOR":!0,"* HEADERS":!0,"* NAME":!0,"A TARGET":!0,
"* CLASS":!0,"* ID":!0,"* STYLE":!0};var Lh={};
function Mh(a){if(mf&&!Jf(9))return[0,0,0,0];var b=Lh.hasOwnProperty(a)?Lh[a]:null;if(b)return b;65536<Object.keys(Lh).length&&(Lh={});var c=[0,0,0,0];b=Nh(a,/\\[0-9A-Fa-f]{6}\s?/g);b=Nh(b,/\\[0-9A-Fa-f]{1,5}\s/g);b=Nh(b,/\\./g);b=b.replace(/:not\(([^\)]*)\)/g,"     $1 ");b=b.replace(/{[^]*/gm,"");b=Oh(b,c,/(\[[^\]]+\])/g,2);b=Oh(b,c,/(#[^\#\s\+>~\.\[:]+)/g,1);b=Oh(b,c,/(\.[^\s\+>~\.\[:]+)/g,2);b=Oh(b,c,/(::[^\s\+>~\.\[:]+|:first-line|:first-letter|:before|:after)/gi,3);b=Oh(b,c,/(:[\w-]+\([^\)]*\))/gi,2);
b=Oh(b,c,/(:[^\s\+>~\.\[:]+)/g,2);b=b.replace(/[\*\s\+>~]/g," ");b=b.replace(/[#\.]/g," ");Oh(b,c,/([^\s\+>~\.\[:]+)/g,3);b=c;return Lh[a]=b}function Oh(a,b,c,d){return a.replace(c,function(e){b[d]+=1;return Array(e.length+1).join(" ")})}function Nh(a,b){return a.replace(b,function(c){return Array(c.length+1).join("A")})};var Ph={rgb:!0,rgba:!0,alpha:!0,rect:!0,image:!0,"linear-gradient":!0,"radial-gradient":!0,"repeating-linear-gradient":!0,"repeating-radial-gradient":!0,"cubic-bezier":!0,matrix:!0,perspective:!0,rotate:!0,rotate3d:!0,rotatex:!0,rotatey:!0,steps:!0,rotatez:!0,scale:!0,scale3d:!0,scalex:!0,scaley:!0,scalez:!0,skew:!0,skewx:!0,skewy:!0,translate:!0,translate3d:!0,translatex:!0,translatey:!0,translatez:!0},Qh=/[\n\f\r"'()*<>]/g,Rh={"\n":"%0a","\f":"%0c","\r":"%0d",'"':"%22","'":"%27","(":"%28",")":"%29",
"*":"%2a","<":"%3c",">":"%3e"};function Sh(a){return Rh[a]}
var Th=function(a,b,c){b=Sc(b);if(""==b)return null;if(0==Tc("url(",b.substr(0,4))){if(!b.endsWith(")")||1<(b?b.split("(").length-1:0)||1<(b?b.split(")").length-1:0)||!c)a=null;else{a:{b=b.substring(4,b.length-1);for(var d=0;2>d;d++){var e="\"'".charAt(d);if(b.charAt(0)==e&&b.charAt(b.length-1)==e){b=b.substring(1,b.length-1);break a}}}a=c?(a=c(b,a))&&"about:invalid#zClosurez"!=oe(a)?'url("'+oe(a).replace(Qh,Sh)+'")':null:null}return a}if(0<b.indexOf("(")){if(/"|'/.test(b))return null;for(a=/([\-\w]+)\(/g;c=
a.exec(b);)if(!(c[1].toLowerCase()in Ph))return null}return b};function Uh(a,b){a=Ia[a];return a&&a.prototype?(b=Object.getOwnPropertyDescriptor(a.prototype,b))&&b.get||null:null}function Vh(a,b){return(a=Ia[a])&&a.prototype&&a.prototype[b]||null}
var Wh=Uh("Element","attributes")||Uh("Node","attributes"),Xh=Vh("Element","hasAttribute"),Yh=Vh("Element","getAttribute"),Zh=Vh("Element","setAttribute"),$h=Vh("Element","removeAttribute"),ai=Vh("Element","getElementsByTagName"),bi=Vh("Element","matches")||Vh("Element","msMatchesSelector"),ci=Uh("Node","nodeName"),di=Uh("Node","nodeType"),ei=Uh("Node","parentNode"),fi=Uh("HTMLElement","style")||Uh("Element","style"),gi=Uh("HTMLStyleElement","sheet"),hi=Vh("CSSStyleDeclaration","getPropertyValue"),
ii=Vh("CSSStyleDeclaration","setProperty");function ji(a,b,c,d){if(a)return a.apply(b);a=b[c];if(!d(a))throw Error("Clobbering detected");return a}function ki(a,b,c,d){if(a)return a.apply(b,d);if(mf&&10>document.documentMode){if(!b[c].call)throw Error("IE Clobbering detected");}else if("function"!=typeof b[c])throw Error("Clobbering detected");return b[c].apply(b,d)}function li(a){return ji(Wh,a,"attributes",function(b){return b instanceof NamedNodeMap})}
function mi(a,b,c){try{ki(Zh,a,"setAttribute",[b,c])}catch(d){if(-1==d.message.indexOf("A security problem occurred"))throw d;}}function ni(a){oi(a);return ji(fi,a,"style",function(b){return b instanceof CSSStyleDeclaration})}function oi(a){if(!(a instanceof HTMLElement))throw Error("Not an HTMLElement");}function pi(a){oi(a);return ji(gi,a,"sheet",function(b){return b instanceof CSSStyleSheet})}function qi(a){return ji(ci,a,"nodeName",function(b){return"string"==typeof b})}
function ri(a){return ji(di,a,"nodeType",function(b){return"number"==typeof b})}function xi(a){return ji(ei,a,"parentNode",function(b){return!(b&&"string"==typeof b.name&&b.name&&"parentnode"==b.name.toLowerCase())})}function yi(a,b){return ki(hi,a,a.getPropertyValue?"getPropertyValue":"getAttribute",[b])||""}function zi(a,b,c){ki(ii,a,a.setProperty?"setProperty":"setAttribute",[b,c])};var Ai=mf&&10>document.documentMode?null:/\s*([^\s'",]+[^'",]*(('([^'\r\n\f\\]|\\[^])*')|("([^"\r\n\f\\]|\\[^])*")|[^'",])*)/g,Bi={"-webkit-border-horizontal-spacing":!0,"-webkit-border-vertical-spacing":!0},Ei=function(a,b,c){var d=[];a=Ci(yc(a.cssRules));cc(a,function(e){if(b&&!/[a-zA-Z][\w-:\.]*/.test(b))throw Error("Invalid container id");if(!(b&&mf&&10==document.documentMode&&/\\['"]/.test(e.selectorText))){var f=b?e.selectorText.replace(Ai,"#"+b+" $1"):e.selectorText,g=d.push;e=Di(e.style,c);
if(-1!=f.indexOf("<"))throw Error("Selector does not allow '<', got: "+f);var h=f.replace(/('|")((?!\1)[^\r\n\f\\]|\\[\s\S])*\1/g,"");if(!/^[-_a-zA-Z0-9#.:* ,>+~[\]()=^$|]+$/.test(h))throw Error("Selector allows only [-_a-zA-Z0-9#.:* ,>+~[\\]()=^$|] and strings, got: "+f);a:{for(var n={"(":")","[":"]"},p=[],r=0;r<h.length;r++){var y=h[r];if(n[y])p.push(n[y]);else if(sd(n,y)&&p.pop()!=y){h=!1;break a}}h=0==p.length}if(!h)throw Error("() and [] in selector must be balanced, got: "+f);if(!(e instanceof
ve)){h="";for(var B in e)if(Object.prototype.hasOwnProperty.call(e,B)){if(!/^[-_a-zA-Z0-9]+$/.test(B))throw Error("Name allows only [-_a-zA-Z0-9], got: "+B);n=e[B];null!=n&&(n=Array.isArray(n)?gc(n,ze).join(" "):ze(n),h+=B+":"+n+";")}e=h?new ve(h,ue):xe}f=f+"{"+we(e).replace(/</g,"\\3C ")+"}";g.call(d,new He(f,Ge))}});return Je(d)},Ci=function(a){return ec(a,function(b){return b instanceof CSSStyleRule||b.type==CSSRule.STYLE_RULE})},Gi=function(a,b,c){a=Fi("<style>"+a+"</style>");return null==a||
null==a.sheet?Ke:Ei(a.sheet,void 0!=b?b:null,c)},Fi=function(a){if(mf&&!Jf(10)||"function"!=typeof Ia.DOMParser)return null;a=Oe("<html><head></head><body>"+a+"</body></html>",null);return(new DOMParser).parseFromString(Ne(a),"text/html").body.children[0]},Di=function(a,b){if(!a)return xe;var c=document.createElement("div").style,d=Hi(a);cc(d,function(e){var f=rf&&e in Bi?e:e.replace(/^-(?:apple|css|epub|khtml|moz|mso?|o|rim|wap|webkit|xv)-(?=[a-z])/i,"");Oc(f,"--")||Oc(f,"var")||(e=yi(a,e),e=Th(f,
e,b),null!=e&&zi(c,f,e))});return new ve(c.cssText||"",ue)},Ji=function(a){var b=Array.from(ki(ai,a,"getElementsByTagName",["STYLE"])),c=Nc(b,function(e){return yc(pi(e).cssRules)});c=Ci(c);c.sort(function(e,f){e=Mh(e.selectorText);a:{f=Mh(f.selectorText);for(var g=Gc,h=Math.min(e.length,f.length),n=0;n<h;n++){var p=g(e[n],f[n]);if(0!=p){e=p;break a}}e=Gc(e.length,f.length)}return-e});a=document.createTreeWalker(a,NodeFilter.SHOW_ELEMENT,null,!1);for(var d;d=a.nextNode();)cc(c,function(e){ki(bi,d,
d.matches?"matches":"msMatchesSelector",[e.selectorText])&&e.style&&Ii(d,e.style)});cc(b,ag)},Ii=function(a,b){var c=Hi(a.style),d=Hi(b);cc(d,function(e){if(!(0<=c.indexOf(e))){var f=yi(b,e);zi(a.style,e,f)}})},Hi=function(a){Sa(a)?a=yc(a):(a=qd(a),tc(a,"cssText"));return a};var Ki="undefined"!=typeof WeakMap&&-1!=WeakMap.toString().indexOf("[native code]"),Li=0,Mi=function(){this.j=[];this.h=[];this.g="data-elementweakmap-index-"+Li++};Mi.prototype.set=function(a,b){if(ki(Xh,a,"hasAttribute",[this.g])){var c=parseInt(ki(Yh,a,"getAttribute",[this.g])||null,10);this.h[c]=b}else c=this.h.push(b)-1,mi(a,this.g,c.toString()),this.j.push(a);return this};
Mi.prototype.get=function(a){if(ki(Xh,a,"hasAttribute",[this.g]))return a=parseInt(ki(Yh,a,"getAttribute",[this.g])||null,10),this.h[a]};Mi.prototype.clear=function(){this.j.forEach(function(a){ki($h,a,"removeAttribute",[this.g])},this);this.j=[];this.h=[]};var Ni=Sg("goog.html.sanitizer.SafeDomTreeProcessor"),Oi=!mf||10<=Number(Mf),Pi=!mf||null==document.documentMode,Qi=function(){};var Ri={APPLET:!0,AUDIO:!0,BASE:!0,BGSOUND:!0,EMBED:!0,FORM:!0,IFRAME:!0,ISINDEX:!0,KEYGEN:!0,LAYER:!0,LINK:!0,META:!0,OBJECT:!0,SCRIPT:!0,SVG:!0,STYLE:!0,TEMPLATE:!0,VIDEO:!0};var Si={A:!0,ABBR:!0,ACRONYM:!0,ADDRESS:!0,AREA:!0,ARTICLE:!0,ASIDE:!0,B:!0,BDI:!0,BDO:!0,BIG:!0,BLOCKQUOTE:!0,BR:!0,BUTTON:!0,CAPTION:!0,CENTER:!0,CITE:!0,CODE:!0,COL:!0,COLGROUP:!0,DATA:!0,DATALIST:!0,DD:!0,DEL:!0,DETAILS:!0,DFN:!0,DIALOG:!0,DIR:!0,DIV:!0,DL:!0,DT:!0,EM:!0,FIELDSET:!0,FIGCAPTION:!0,FIGURE:!0,FONT:!0,FOOTER:!0,FORM:!0,H1:!0,H2:!0,H3:!0,H4:!0,H5:!0,H6:!0,HEADER:!0,HGROUP:!0,HR:!0,I:!0,IMG:!0,INPUT:!0,INS:!0,KBD:!0,LABEL:!0,LEGEND:!0,LI:!0,MAIN:!0,MAP:!0,MARK:!0,MENU:!0,METER:!0,NAV:!0,
NOSCRIPT:!0,OL:!0,OPTGROUP:!0,OPTION:!0,OUTPUT:!0,P:!0,PRE:!0,PROGRESS:!0,Q:!0,S:!0,SAMP:!0,SECTION:!0,SELECT:!0,SMALL:!0,SOURCE:!0,SPAN:!0,STRIKE:!0,STRONG:!0,STYLE:!0,SUB:!0,SUMMARY:!0,SUP:!0,TABLE:!0,TBODY:!0,TD:!0,TEXTAREA:!0,TFOOT:!0,TH:!0,THEAD:!0,TIME:!0,TR:!0,TT:!0,U:!0,UL:!0,VAR:!0,WBR:!0};var Ti={"ANNOTATION-XML":!0,"COLOR-PROFILE":!0,"FONT-FACE":!0,"FONT-FACE-SRC":!0,"FONT-FACE-URI":!0,"FONT-FACE-FORMAT":!0,"FONT-FACE-NAME":!0,"MISSING-GLYPH":!0},Xi=function(a){a=a||new Ui;Vi(a);this.g=vd(a.g);this.m=vd(a.D);this.h=vd(a.F);this.u=a.C;cc(a.H,function(b){if(!Oc(b,"data-"))throw new Yb('Only "data-" attributes allowed, got: %s.',[b]);if(Oc(b,"data-sanitizer-"))throw new Yb('Attributes with "%s" prefix are not allowed, got: %s.',["data-sanitizer-",b]);this.g["* "+b.toUpperCase()]=Wi},
this);cc(a.G,function(b){b=b.toUpperCase();if(-1==b.indexOf("-")||Ti[b])throw new Yb("Only valid custom element tag names allowed, got: %s.",[b]);this.h[b]=!0},this);this.C=a.j;this.l=a.u;this.j=null;this.s=a.s};w(Xi,Qi);
var Yi=function(a){return function(b,c){return(b=a(Sc(b),c))&&"about:invalid#zClosurez"!=oe(b)?oe(b):null}},Ui=function(){this.g={};cc([Jh,Kh],function(a){cc(qd(a),function(b){this.g[b]=Wi},this)},this);this.h={};this.H=[];this.G=[];this.D=vd(Ri);this.F=vd(Si);this.C=!1;this.O=te;this.L=this.m=this.J=this.j=Jd;this.u=null;this.l=this.s=!1},Zi=function(a,b){return function(c,d,e,f){c=a(c,d,e,f);return null==c?null:b(c,d,e,f)}},$i=function(a,b,c,d){a[c]&&!b[c]&&(a[c]=Zi(a[c],d))};Ui.prototype.ca=function(){return new Xi(this)};
var Vi=function(a){if(a.l)throw Error("HtmlSanitizer.Builder.build() can only be used once.");$i(a.g,a.h,"* USEMAP",aj);var b=Yi(a.O);cc(["* ACTION","* CITE","* HREF"],function(d){$i(this.g,this.h,d,b)},a);var c=Yi(a.j);cc(["* LONGDESC","* SRC","LINK HREF"],function(d){$i(this.g,this.h,d,c)},a);cc(["* FOR","* HEADERS","* NAME"],function(d){$i(this.g,this.h,d,bb(bj,this.J))},a);$i(a.g,a.h,"A TARGET",bb(cj,["_blank","_self"]));$i(a.g,a.h,"* CLASS",bb(dj,a.m));$i(a.g,a.h,"* ID",bb(ej,a.m));$i(a.g,a.h,
"* STYLE",bb(a.L,c));a.l=!0},fj=function(a,b){a||(a="*");return(a+" "+b).toUpperCase()},Wi=function(a){return Sc(a)},cj=function(a,b){b=Sc(b);return nc(a,b.toLowerCase())?b:null},aj=function(a){return(a=Sc(a))&&"#"==a.charAt(0)?a:null},bj=function(a,b,c){return a(Sc(b),c)},dj=function(a,b,c){b=b.split(/(?:\s+)/);for(var d=[],e=0;e<b.length;e++){var f=a(b[e],c);f&&d.push(f)}return 0==d.length?null:d.join(" ")},ej=function(a,b,c){return a(Sc(b),c)},gj=function(a,b){var c=b.data;(b=xi(b))&&"style"==
qi(b).toLowerCase()&&!("STYLE"in a.m)&&"STYLE"in a.h&&(c=Ie(Gi(c,a.j,$a(function(d,e){return this.C(d,{NS:e})},a))));return document.createTextNode(c)},hj=function(a){var b=(new Ui).ca();var c=!("STYLE"in b.m)&&"STYLE"in b.h;c="*"==b.l&&c?"sanitizer-"+$e():b.l;b.j=c;if(Oi){c=a;if(Oi){a=Zf(document,"SPAN");b.j&&"*"==b.l&&(a.id=b.j);b.s&&(c=Fi("<div>"+c+"</div>"),Ji(c),c=c.innerHTML);c=Oe(c,null);var d=document.createElement("template");if(Pi&&"content"in d)Ue(d,c),d=d.content;else{var e=document.implementation.createHTMLDocument("x");
d=e.body;Ue(e.body,c)}c=document.createTreeWalker(d,NodeFilter.SHOW_ELEMENT|NodeFilter.SHOW_TEXT,null,!1);for(d=Ki?new WeakMap:new Mi;e=c.nextNode();){c:{var f=b;var g=e;var h=ri(g);switch(h){case 3:g=gj(f,g);break c;case 1:h=g;1==ri(h)||Zb("Expected Node of type Element but got Node of type %s",ri(h));g=f;f=h;if("TEMPLATE"==qi(f).toUpperCase())g=null;else{h=qi(f).toUpperCase();if(h in g.m)var n=null;else g.h[h]?n=document.createElement(h):(n=Zf(document,"SPAN"),g.u&&mi(n,"data-sanitizer-original-tag",
h.toLowerCase()));if(n){var p=n,r=li(f);if(null!=r)for(var y=0;h=r[y];y++)if(h.specified){var B=g;var C=f,L=h,Q=L.name;if(Oc(Q,"data-sanitizer-"))B=null;else{var fa=qi(C);L=L.value;var ab={tagName:Sc(fa).toLowerCase(),attributeName:Sc(Q).toLowerCase()},pb={dw:void 0};"style"==ab.attributeName&&(pb.dw=ni(C));C=fj(fa,Q);C in B.g?(B=B.g[C],B=B(L,ab,pb)):(Q=fj(null,Q),Q in B.g?(B=B.g[Q],B=B(L,ab,pb)):B=null)}null!==B&&mi(p,h.name,B)}g=n}else g=null}break c;default:Vg(Ni,"Dropping unknown node type: "+
h),g=null}}if(g){if(1==ri(g)&&d.set(e,g),e=xi(e),f=!1,e)h=ri(e),n=qi(e).toLowerCase(),p=xi(e),11!=h||p?"body"==n&&p&&(h=xi(p))&&!xi(h)&&(f=!0):f=!0,h=null,f||!e?h=a:1==ri(e)&&(h=d.get(e)),h.content&&(h=h.content),h.appendChild(g)}else $f(e)}d.clear&&d.clear();b=a}else b=Zf(document,"SPAN");0<li(b).length&&(a=Zf(document,"SPAN"),a.appendChild(b),b=a);b=(new XMLSerializer).serializeToString(b);b=b.slice(b.indexOf(">")+1,b.lastIndexOf("</"))}else b="";return Oe(b,null)};if("undefined"!=typeof angular){var ij=angular.module("chrome_18n",[]);chrome.runtime&&chrome.runtime.getManifest&&chrome.runtime.getManifest().default_locale&&ij.directive("angularMessage",function(){return{restrict:"E",replace:!0,controller:["$scope",function(a){var b=this;this.Jk=this.qh=null;a.dirForText=function(c){b.qh||(b.qh=chrome.i18n.getMessage("@@bidi_dir")||"ltr");b.Jk||(b.Jk=new Yg("rtl"==b.qh));var d=b.Jk,e,f=e=0,g=!1;c=(c||"").split(de);for(var h=0;h<c.length;h++){var n=c[h];Yd.test(n)?
(e++,f++):Zd.test(n)?g=!0:Xd.test(n)?f++:ee.test(n)&&(g=!0)}e=0==f?g?1:0:.4<e/f?-1:1;return-1==(0==e?d.g:e)?"rtl":"ltr"}}],compile:function(a,b){b=b.key;var c=null,d=document.createElement("amr");b&&!b.match(/^\d+$/)&&(b=chrome.i18n.getMessage(b),null==b&&d.setAttribute("id","missing"));if(b){var e=chrome.i18n.getMessage(b+"_ph");c=[];if(null!=e)for(c=e.split("\ue000"),e=0;e<c.length;++e)c[e]=c[e].replace(/^{{(.*)}}$/,'<amrp dir="{{dirForText($1)}}">{{$1}}</amrp>');c=chrome.i18n.getMessage(b,c)}else d.setAttribute("r",
"nokey");c?Ve(d,hj(c)):(d.setAttribute("tl","false"),Ve(d,hj(a.html())));a.replaceWith(d)}}})};var kj=function(a,b){var c=this;this.s=b;this.g=a;this.g.top=a;this.C=[];this.l=!1;this.h=new ch;this.g.videoSmoothnessRatings=this.Am(oh,jh,kh,lh,mh,nh);this.g.videoQualityRatings=this.Am(oh,ph,qh,rh,sh,th);this.g.audioQualityRatings=this.Am(oh,uh,vh,wh,xh,yh);this.C=[{value:"Bug",desc:dh},{value:"FeatureRequest",desc:eh},{value:"MirroringQuality",desc:fh},{value:"Discovery",desc:hh},{value:"Other",desc:ih}];this.g.feedbackTypes=this.C;this.g.includeFineLogs=!0;this.g.feedbackType="Bug";this.g.sendFeedback=
this.OB.bind(this);this.g.cancel=this.Uv.bind(this);this.g.attachLogsClick=this.m.bind(this);this.g.viewLogs=this.F.bind(this);this.g.$watchGroup("videoSmoothness videoQuality audioQuality feedbackDescription comments feedbackType".split(" "),this.Xv.bind(this));this.g.sufficientFeedback=!1;this.g.$watch("attachLogs",this.m.bind(this));this.g.attachLogs=!0;this.u=$e();this.g.userEmail="";chrome.identity.getProfileUserInfo(function(d){c.g.userEmail=d.email;jj(c)});this.g.yourAnswerText=Ih;this.g.language=
chrome.i18n&&chrome.i18n.getUILanguage?chrome.i18n.getUILanguage():chrome.runtime.getManifest().default_locale;this.g.requestLogsInProgress=!1;this.g.mrVersion=chrome.runtime.getManifest().version};k=kj.prototype;k.Am=function(a){for(var b=[],c=1;c<arguments.length;c++)b.push(new lj(c,arguments[c]));b.push(new lj(0,arguments[0]));return b};k.Uv=function(){this.g.feedbackDescription&&!confirm(zh)||window.close()};
k.Xv=function(){var a=this.g.feedbackType;this.g.sufficientFeedback="MirroringQuality"==a?this.g.videoSmoothness||this.g.videoQuality||this.g.audioQuality||this.g.comments:"Discovery"==a?this.g.visibleInSetup||this.g.comments:!!this.g.feedbackDescription};
k.OB=function(){if(this.g.sufficientFeedback){var a=this.g.feedbackType,b="";"MirroringQuality"==a?(this.g.videoSmoothness&&(b+="\nVideo Smoothness: "+this.g.videoSmoothness),this.g.videoQuality&&(b+="\nVideo Quality: "+this.g.videoQuality),this.g.audioQuality&&(b+="\nAudio: "+this.g.audioQuality),this.g.projectedContentUrl&&(b+="\nProjected Content/URL: "+this.g.projectedContentUrl),this.g.comments&&(b+="\nComments: "+this.g.comments)):"Discovery"==a?(this.g.visibleInSetup&&(b+="\nChromecast Visible in Setup: "+
this.g.visibleInSetup),this.g.hasNetworkSoftware&&(b+="\nUsing VPN/proxy/firewall/NAS Software: "+this.g.hasNetworkSoftware),this.g.networkDescription&&(b+="\nNetwork Description: "+this.g.networkDescription),this.g.comments&&(b+="\nComments: "+this.g.comments)):b=this.g.feedbackDescription;a="Type: "+a+"\n\n"+b;this.g.sendDialogText=Ah;this.g.okButton=Hh;this.g.feedbackSent=!1;this.s.show({locals:{fT:this.g.feedbackSent,TU:this.g.sendDialogText,EA:this.g.okButton},scope:this.g,preserveScope:!0,bindToController:!0,
template:'<md-dialog id="feedback-confirmation"><md-dialog-content><div id="send-feedback-text">{{sendDialogText}}</div><md-dialog-actions><md-button class="md-raised md-primary"ng-disabled="!feedbackSent" ng-click="closeWindow()">{{okButton}}</md-button></md-dialog-actions></md-dialog-content></md-dialog>',controller:this.j});this.Tq(a,Date.now())}};k.Tq=function(a,b){var c=Date.now();!this.g.requestLogsInProgress||5E3<c-b?mj(this,a):setTimeout(this.Tq.bind(this),1E3,a,b)};
var mj=function(a,b){var c=0,d=function(f,g,h){h?f(!0):(a.g.sendDialogText=Dh,jj(a),g(Error("Failed to send")))},e=chrome.declarativeWebRequest?"MrTeamfood":"MRStable";(new $g(function(){c++;return new Promise(function(f,g){var h=a.g.userEmail,n=a.h;f=d.bind(null,f,g);g=chrome.runtime.getManifest();bh({productId:85561,bucket:e,flow:"submit",serverUri:"https://www.google.com/tools/feedback",allowNonLoggedInFeedback:!0,locale:g.default_locale,enableAnonymousFeedback:!h,report:{description:b},callback:f},
{version:g.version,description:g.description,user_email:h||"NA",logs:n.hd||"NA",external_logs:n.g||"NA",device_model:n.modelName||"NA",receiver_version:n.u||"NA",dash_report_url:n.l||"NA",cast_device_counts:n.h,dial_device_counts:n.j,mirroring_service_enabled:n.m,native_cast_mrp_enabled:n.s,native_dial_mrp_enabled:n.C})})},1E4,4)).start().then(function(){Qb("MediaRouter.Ui.Action.Feedback");a.g.sendDialogText=Ch;a.g.feedbackSent=!0;jj(a)},function(){a.g.sendDialogText=Bh;a.g.feedbackSent=!0;jj(a)})};
kj.prototype.m=function(){var a=this;this.h=new ch;this.g.attachLogs&&(this.g.requestLogsInProgress=!0,chrome.runtime.sendMessage(new Zg(this.u,"retrieve_log_data"),function(b){a.g.requestLogsInProgress=!1;a.h.hd=b.logs||"no extension";a.h.hd+="\n";a.h.hd+=b.mediaSinkServiceStatus||"no media sink service status from browser";a.h.hd+="\n";a.h.hd+=b.mediaRouterLogs||"no Media Router logs from the browser";b.castStreamingLogs&&(a.h.l=b.castStreamingLogs);b.castDeviceCounts&&(a.h.h=b.castDeviceCounts);
b.dialDeviceCounts&&(a.h.j=b.dialDeviceCounts);a.h.m=!!b.mirroringServiceEnabled;a.h.s=!!b.nativeCastMrpEnabled;a.h.C=!!b.nativeDialMrpEnabled;if(b=b.device)if(b.model&&(a.h.modelName=b.model),b.version&&(a.h.u=b.version),!a.l){var c=$e();a.l=!0;a.h.g=Cb(b.ip,c,a.D.bind(a))}}))};
kj.prototype.F=function(){this.g.logs=this.h.hd;this.g.logsHeader=Eh;this.g.sendLogs=Fh;this.g.fineLogsWarning=Gh;this.g.okButton=Hh;this.s.show({locals:{tS:this.g.attachLogs,hd:this.g.logs,zT:this.g.includeFineLogs,cU:this.g.logsHeader,UU:this.g.sendLogs,gT:this.g.fineLogsWarning,EA:this.g.okButton},scope:this.g,preserveScope:!0,bindToController:!0,clickOutsideToClose:!0,template:'<md-dialog><md-dialog-content id="logs-dialog"><div class="subheading">{{logsHeader}}</div><div ng-show="includeFineLogs && attachLogs"id="feedback-fine-log-warning" class="informative">{{fineLogsWarning}}</div><pre>{{logs}}</pre><div class="send-logs"><md-checkbox type="checkbox" ng-model="attachLogs"ng-change="attachLogsClick()"><span>{{sendLogs}}</span></md-checkbox></div><md-dialog-actions><md-button class="md-raised md-primary"ng-click="closeDialog()">{{okButton}}</md-button></md-dialog-actions></md-dialog-content></md-dialog>',
controller:this.j})};kj.prototype.D=function(a,b){this.l=!1;this.h.g="error"==a?"":b;this.g.attachLogs||(this.h.g="");jj(this)};var jj=function(a){a.g.$$phase||a.g.$apply()};kj.prototype.j=function(a,b){a.closeWindow=function(){window.close()};a.closeDialog=function(){b.hide()}};kj.prototype.j.$inject=["$scope","$mdDialog"];var lj=function(a,b){this.id=a;this.desc=b;this.text=0==a?b:a+" ("+b+")"};
angular.module("feedbackApp","chrome_18n material.components.button material.components.checkbox material.components.dialog material.components.input material.components.radioButton".split(" ")).controller("FeedbackCtrl",["$scope","$mdDialog",kj]);v("ng.safehtml.googSceHelper.isGoogHtmlType",function(a){return a&&a.le?!0:!1});v("ng.safehtml.googSceHelper.isCOMPILED",function(){return!0});v("ng.safehtml.googSceHelper.unwrapAny",function(a){if(a instanceof ge)return he(a).toString();if(a instanceof Me)return Ne(a).toString();if(a instanceof ne)return oe(a);if(a instanceof ve)return we(a);if(a instanceof Vd)return Wd(a).toString();throw Error();});
v("ng.safehtml.googSceHelper.unwrapGivenContext",function(a,b){if("html"==a)return Ne(b).toString();if("resourceUrl"==a||"templateUrl"==a)return he(b).toString();if("url"==a)return b instanceof ge?he(b).toString():oe(b);if("css"==a)return we(b);if("js"==a)return Wd(b).toString();throw Error();});
