'use strict';var Kg=function(a,b,c){a.timeOfStartCall=(new Date).getTime();var d=c||Fa,e=d.document,f=a.nonce||Ia(d);f&&!a.nonce&&(a.nonce=f);if("help"==a.flow){var g=Ka("document.location.href",d);!a.helpCenterContext&&g&&(a.helpCenterContext=g.substring(0,1200));g=!0;if(b&&JSON&&JSON.stringify){var h=JSON.stringify(b);(g=1200>=h.length)&&(a.psdJson=h)}g||(b={invalidPsd:!0})}g=[a,b,c];d.GOOGLE_FEEDBACK_START_ARGUMENTS=g;h=a.serverUri||"//www.google.com/tools/feedback";var l=d.GOOGLE_FEEDBACK_START;if(a.forceNewHelpPanel){var q=
Of(Ef(e),"SCRIPT");f&&q.setAttribute("nonce",f);q.onload=function(){d.startHelpPanel({helpcenter:a.helpCenterPath.split("/")[1],apiKey:"testpage",locale:a.locale,enableSendFeedback:a.enableSendFeedback||!1,helpApiData:{helpApiConfig:a,productData:b,productWindow:c}})};Ie(q,Xd(Jd(new Id(Gd,"https://www.gstatic.com/support/help/staging/main_frame/help_panel_staging_binary.js"))));e.body.appendChild(q)}else if(l)l.apply(d,g);else{g=h+"/load.js?";for(q in a)h=a[q],null==h||Pa(h)||(g+=encodeURIComponent(q)+
"="+encodeURIComponent(h)+"&");q=Of(Ef(e),"SCRIPT");f&&q.setAttribute("nonce",f);Ie(q,Qf(g));e.body.appendChild(q)}};v("userfeedback.api.startFeedback",Kg);var Lg=function(){this.j=this.h=this.u=this.modelName=this.l=this.g=this.Uc="";this.s=this.m=this.C=!1};var Mg=chrome.i18n.getMessage("4163185390680253103"),Ng=chrome.i18n.getMessage("492097680647953484"),Og=chrome.i18n.getMessage("2575016469622936324"),Pg=chrome.i18n.getMessage("128276876460319075"),Qg=chrome.i18n.getMessage("3326722026796849289"),Rg=chrome.i18n.getMessage("1018984561488520517"),Sg=chrome.i18n.getMessage("8205999658352447129"),Tg=chrome.i18n.getMessage("5723583529370342957"),Ug=chrome.i18n.getMessage("1550904064710828958"),Vg=chrome.i18n.getMessage("5014364904504073524"),Wg=chrome.i18n.getMessage("2194670894476780934"),
Xg=chrome.i18n.getMessage("6614468912728530636"),Yg=chrome.i18n.getMessage("5910595154486533449"),Zg=chrome.i18n.getMessage("5363086287710390513"),$g=chrome.i18n.getMessage("244647017322945605"),ah=chrome.i18n.getMessage("5375576275991472719"),bh=chrome.i18n.getMessage("4592127349908255218"),ch=chrome.i18n.getMessage("843316808366399491"),dh=chrome.i18n.getMessage("5699813974548050528"),eh=chrome.i18n.getMessage("8515148417333877999"),fh=chrome.i18n.getMessage("1636686747687494376"),gh=chrome.i18n.getMessage("4148300086676792937"),
hh=chrome.i18n.getMessage("3219866268410307919"),ih=chrome.i18n.getMessage("9211708838274008657"),jh=chrome.i18n.getMessage("8706273405040403641"),kh=chrome.i18n.getMessage("4756056595565370923"),lh=chrome.i18n.getMessage("7876724262035435114"),mh=chrome.i18n.getMessage("5485620192329479690"),nh=chrome.i18n.getMessage("6963873398546068901"),oh=chrome.i18n.getMessage("3567591856726172993"),ph=chrome.i18n.getMessage("3239956785410157548");/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var qh={"* ARIA-CHECKED":!0,"* ARIA-COLCOUNT":!0,"* ARIA-COLINDEX":!0,"* ARIA-CONTROLS":!0,"* ARIA-DESCRIBEDBY":!0,"* ARIA-DISABLED":!0,"* ARIA-EXPANDED":!0,"* ARIA-GOOG-EDITABLE":!0,"* ARIA-HASPOPUP":!0,"* ARIA-HIDDEN":!0,"* ARIA-LABEL":!0,"* ARIA-LABELLEDBY":!0,"* ARIA-MULTILINE":!0,"* ARIA-MULTISELECTABLE":!0,"* ARIA-ORIENTATION":!0,"* ARIA-PLACEHOLDER":!0,"* ARIA-READONLY":!0,"* ARIA-REQUIRED":!0,"* ARIA-ROLEDESCRIPTION":!0,"* ARIA-ROWCOUNT":!0,"* ARIA-ROWINDEX":!0,"* ARIA-SELECTED":!0,"* ABBR":!0,
"* ACCEPT":!0,"* ACCESSKEY":!0,"* ALIGN":!0,"* ALT":!0,"* AUTOCOMPLETE":!0,"* AXIS":!0,"* BGCOLOR":!0,"* BORDER":!0,"* CELLPADDING":!0,"* CELLSPACING":!0,"* CHAROFF":!0,"* CHAR":!0,"* CHECKED":!0,"* CLEAR":!0,"* COLOR":!0,"* COLSPAN":!0,"* COLS":!0,"* COMPACT":!0,"* COORDS":!0,"* DATETIME":!0,"* DIR":!0,"* DISABLED":!0,"* ENCTYPE":!0,"* FACE":!0,"* FRAME":!0,"* HEIGHT":!0,"* HREFLANG":!0,"* HSPACE":!0,"* ISMAP":!0,"* LABEL":!0,"* LANG":!0,"* MAX":!0,"* MAXLENGTH":!0,"* METHOD":!0,"* MULTIPLE":!0,
"* NOHREF":!0,"* NOSHADE":!0,"* NOWRAP":!0,"* OPEN":!0,"* READONLY":!0,"* REQUIRED":!0,"* REL":!0,"* REV":!0,"* ROLE":!0,"* ROWSPAN":!0,"* ROWS":!0,"* RULES":!0,"* SCOPE":!0,"* SELECTED":!0,"* SHAPE":!0,"* SIZE":!0,"* SPAN":!0,"* START":!0,"* SUMMARY":!0,"* TABINDEX":!0,"* TITLE":!0,"* TYPE":!0,"* VALIGN":!0,"* VALUE":!0,"* VSPACE":!0,"* WIDTH":!0},rh={"* USEMAP":!0,"* ACTION":!0,"* CITE":!0,"* HREF":!0,"* LONGDESC":!0,"* SRC":!0,"LINK HREF":!0,"* FOR":!0,"* HEADERS":!0,"* NAME":!0,"A TARGET":!0,
"* CLASS":!0,"* ID":!0,"* STYLE":!0};var sh={};
function th(a){if($e&&!vf(9))return[0,0,0,0];var b=sh.hasOwnProperty(a)?sh[a]:null;if(b)return b;65536<Object.keys(sh).length&&(sh={});var c=[0,0,0,0];b=uh(a,/\\[0-9A-Fa-f]{6}\s?/g);b=uh(b,/\\[0-9A-Fa-f]{1,5}\s/g);b=uh(b,/\\./g);b=b.replace(/:not\(([^\)]*)\)/g,"     $1 ");b=b.replace(/{[^]*/gm,"");b=vh(b,c,/(\[[^\]]+\])/g,2);b=vh(b,c,/(#[^\#\s\+>~\.\[:]+)/g,1);b=vh(b,c,/(\.[^\s\+>~\.\[:]+)/g,2);b=vh(b,c,/(::[^\s\+>~\.\[:]+|:first-line|:first-letter|:before|:after)/gi,3);b=vh(b,c,/(:[\w-]+\([^\)]*\))/gi,2);
b=vh(b,c,/(:[^\s\+>~\.\[:]+)/g,2);b=b.replace(/[\*\s\+>~]/g," ");b=b.replace(/[#\.]/g," ");vh(b,c,/([^\s\+>~\.\[:]+)/g,3);b=c;return sh[a]=b}function vh(a,b,c,d){return a.replace(c,function(e){b[d]+=1;return Array(e.length+1).join(" ")})}function uh(a,b){return a.replace(b,function(c){return Array(c.length+1).join("A")})};var wh={rgb:!0,rgba:!0,alpha:!0,rect:!0,image:!0,"linear-gradient":!0,"radial-gradient":!0,"repeating-linear-gradient":!0,"repeating-radial-gradient":!0,"cubic-bezier":!0,matrix:!0,perspective:!0,rotate:!0,rotate3d:!0,rotatex:!0,rotatey:!0,steps:!0,rotatez:!0,scale:!0,scale3d:!0,scalex:!0,scaley:!0,scalez:!0,skew:!0,skewx:!0,skewy:!0,translate:!0,translate3d:!0,translatex:!0,translatey:!0,translatez:!0},xh=/[\n\f\r"'()*<>]/g,yh={"\n":"%0a","\f":"%0c","\r":"%0d",'"':"%22","'":"%27","(":"%28",")":"%29",
"*":"%2a","<":"%3c",">":"%3e"};function zh(a){return yh[a]}
var Ah=function(a,b,c){b=Kc(b);if(""==b)return null;if(0==Lc("url(",b.substr(0,4))){if(!b.endsWith(")")||1<(b?b.split("(").length-1:0)||1<(b?b.split(")").length-1:0)||!c)a=null;else{a:{b=b.substring(4,b.length-1);for(var d=0;2>d;d++){var e="\"'".charAt(d);if(b.charAt(0)==e&&b.charAt(b.length-1)==e){b=b.substring(1,b.length-1);break a}}}a=c?(a=c(b,a))&&"about:invalid#zClosurez"!=ae(a)?'url("'+ae(a).replace(xh,zh)+'")':null:null}return a}if(0<b.indexOf("(")){if(/"|'/.test(b))return null;for(a=/([\-\w]+)\(/g;c=
a.exec(b);)if(!(c[1].toLowerCase()in wh))return null}return b};function Bh(a,b){a=Fa[a];return a&&a.prototype?(b=Object.getOwnPropertyDescriptor(a.prototype,b))&&b.get||null:null}function Ch(a,b){return(a=Fa[a])&&a.prototype&&a.prototype[b]||null}
var Dh=Bh("Element","attributes")||Bh("Node","attributes"),Eh=Ch("Element","hasAttribute"),Fh=Ch("Element","getAttribute"),Gh=Ch("Element","setAttribute"),Hh=Ch("Element","removeAttribute"),Ih=Ch("Element","getElementsByTagName"),Jh=Ch("Element","matches")||Ch("Element","msMatchesSelector"),Kh=Bh("Node","nodeName"),Lh=Bh("Node","nodeType"),Mh=Bh("Node","parentNode"),Nh=Bh("HTMLElement","style")||Bh("Element","style"),Oh=Bh("HTMLStyleElement","sheet"),Ph=Ch("CSSStyleDeclaration","getPropertyValue"),
Qh=Ch("CSSStyleDeclaration","setProperty");function Rh(a,b,c,d){if(a)return a.apply(b);a=b[c];if(!d(a))throw Error("Clobbering detected");return a}function Sh(a,b,c,d){if(a)return a.apply(b,d);if($e&&10>document.documentMode){if(!b[c].call)throw Error("IE Clobbering detected");}else if("function"!=typeof b[c])throw Error("Clobbering detected");return b[c].apply(b,d)}function Th(a){return Rh(Dh,a,"attributes",function(b){return b instanceof NamedNodeMap})}
function Uh(a,b,c){try{Sh(Gh,a,"setAttribute",[b,c])}catch(d){if(-1==d.message.indexOf("A security problem occurred"))throw d;}}function Vh(a){Wh(a);return Rh(Nh,a,"style",function(b){return b instanceof CSSStyleDeclaration})}function Wh(a){if(!(a instanceof HTMLElement))throw Error("Not an HTMLElement");}function Xh(a){Wh(a);return Rh(Oh,a,"sheet",function(b){return b instanceof CSSStyleSheet})}function Yh(a){return Rh(Kh,a,"nodeName",function(b){return"string"==typeof b})}
function Zh(a){return Rh(Lh,a,"nodeType",function(b){return"number"==typeof b})}function $h(a){return Rh(Mh,a,"parentNode",function(b){return!(b&&"string"==typeof b.name&&b.name&&"parentnode"==b.name.toLowerCase())})}function ai(a,b){return Sh(Ph,a,a.getPropertyValue?"getPropertyValue":"getAttribute",[b])||""}function bi(a,b,c){Sh(Qh,a,a.setProperty?"setProperty":"setAttribute",[b,c])};var ci=$e&&10>document.documentMode?null:/\s*([^\s'",]+[^'",]*(('([^'\r\n\f\\]|\\[^])*')|("([^"\r\n\f\\]|\\[^])*")|[^'",])*)/g,di={"-webkit-border-horizontal-spacing":!0,"-webkit-border-vertical-spacing":!0},gi=function(a,b,c){var d=[];a=ei(tc(a.cssRules));Zb(a,function(e){if(b&&!/[a-zA-Z][\w-:\.]*/.test(b))throw Error("Invalid container id");if(!(b&&$e&&10==document.documentMode&&/\\['"]/.test(e.selectorText))){var f=b?e.selectorText.replace(ci,"#"+b+" $1"):e.selectorText;d.push(ue(f,fi(e.style,
c)))}});return we(d)},ei=function(a){return ac(a,function(b){return b instanceof CSSStyleRule||b.type==CSSRule.STYLE_RULE})},ii=function(a,b,c){a=hi("<style>"+a+"</style>");return null==a||null==a.sheet?xe:gi(a.sheet,void 0!=b?b:null,c)},hi=function(a){if($e&&!vf(10)||"function"!=typeof Fa.DOMParser)return null;a=Be("<html><head></head><body>"+a+"</body></html>",null);return(new DOMParser).parseFromString(Ae(a),"text/html").body.children[0]},fi=function(a,b){if(!a)return je;var c=document.createElement("div").style,
d=ji(a);Zb(d,function(e){var f=cf&&e in di?e:e.replace(/^-(?:apple|css|epub|khtml|moz|mso?|o|rim|wap|webkit|xv)-(?=[a-z])/i,"");Hc(f,"--")||Hc(f,"var")||(e=ai(a,e),e=Ah(f,e,b),null!=e&&bi(c,f,e))});return new he(c.cssText||"",ge)},li=function(a){var b=Array.from(Sh(Ih,a,"getElementsByTagName",["STYLE"])),c=Gc(b,function(e){return tc(Xh(e).cssRules)});c=ei(c);c.sort(function(e,f){e=th(e.selectorText);a:{f=th(f.selectorText);for(var g=Ac,h=Math.min(e.length,f.length),l=0;l<h;l++){var q=g(e[l],f[l]);
if(0!=q){e=q;break a}}e=Ac(e.length,f.length)}return-e});a=document.createTreeWalker(a,NodeFilter.SHOW_ELEMENT,null,!1);for(var d;d=a.nextNode();)Zb(c,function(e){Sh(Jh,d,d.matches?"matches":"msMatchesSelector",[e.selectorText])&&e.style&&ki(d,e.style)});Zb(b,Mf)},ki=function(a,b){var c=ji(a.style),d=ji(b);Zb(d,function(e){if(!(0<=c.indexOf(e))){var f=ai(b,e);bi(a.style,e,f)}})},ji=function(a){Oa(a)?a=tc(a):(a=gd(a),oc(a,"cssText"));return a};var mi="undefined"!=typeof WeakMap&&-1!=WeakMap.toString().indexOf("[native code]"),ni=0,oi=function(){this.j=[];this.h=[];this.g="data-elementweakmap-index-"+ni++};oi.prototype.set=function(a,b){if(Sh(Eh,a,"hasAttribute",[this.g])){var c=parseInt(Sh(Fh,a,"getAttribute",[this.g])||null,10);this.h[c]=b}else c=this.h.push(b)-1,Uh(a,this.g,c.toString()),this.j.push(a);return this};
oi.prototype.get=function(a){if(Sh(Eh,a,"hasAttribute",[this.g]))return a=parseInt(Sh(Fh,a,"getAttribute",[this.g])||null,10),this.h[a]};oi.prototype.clear=function(){this.j.forEach(function(a){Sh(Hh,a,"removeAttribute",[this.g])},this);this.j=[];this.h=[]};var pi=zg("goog.html.sanitizer.SafeDomTreeProcessor"),qi=!$e||10<=Number(yf),ri=!$e||null==document.documentMode,si=function(){};var ti={APPLET:!0,AUDIO:!0,BASE:!0,BGSOUND:!0,EMBED:!0,FORM:!0,IFRAME:!0,ISINDEX:!0,KEYGEN:!0,LAYER:!0,LINK:!0,META:!0,OBJECT:!0,SCRIPT:!0,SVG:!0,STYLE:!0,TEMPLATE:!0,VIDEO:!0};var ui={A:!0,ABBR:!0,ACRONYM:!0,ADDRESS:!0,AREA:!0,ARTICLE:!0,ASIDE:!0,B:!0,BDI:!0,BDO:!0,BIG:!0,BLOCKQUOTE:!0,BR:!0,BUTTON:!0,CAPTION:!0,CENTER:!0,CITE:!0,CODE:!0,COL:!0,COLGROUP:!0,DATA:!0,DATALIST:!0,DD:!0,DEL:!0,DETAILS:!0,DFN:!0,DIALOG:!0,DIR:!0,DIV:!0,DL:!0,DT:!0,EM:!0,FIELDSET:!0,FIGCAPTION:!0,FIGURE:!0,FONT:!0,FOOTER:!0,FORM:!0,H1:!0,H2:!0,H3:!0,H4:!0,H5:!0,H6:!0,HEADER:!0,HGROUP:!0,HR:!0,I:!0,IMG:!0,INPUT:!0,INS:!0,KBD:!0,LABEL:!0,LEGEND:!0,LI:!0,MAIN:!0,MAP:!0,MARK:!0,MENU:!0,METER:!0,NAV:!0,
NOSCRIPT:!0,OL:!0,OPTGROUP:!0,OPTION:!0,OUTPUT:!0,P:!0,PRE:!0,PROGRESS:!0,Q:!0,S:!0,SAMP:!0,SECTION:!0,SELECT:!0,SMALL:!0,SOURCE:!0,SPAN:!0,STRIKE:!0,STRONG:!0,STYLE:!0,SUB:!0,SUMMARY:!0,SUP:!0,TABLE:!0,TBODY:!0,TD:!0,TEXTAREA:!0,TFOOT:!0,TH:!0,THEAD:!0,TIME:!0,TR:!0,TT:!0,U:!0,UL:!0,VAR:!0,WBR:!0};var vi={"ANNOTATION-XML":!0,"COLOR-PROFILE":!0,"FONT-FACE":!0,"FONT-FACE-SRC":!0,"FONT-FACE-URI":!0,"FONT-FACE-FORMAT":!0,"FONT-FACE-NAME":!0,"MISSING-GLYPH":!0},zi=function(a){a=a||new wi;xi(a);this.g=ld(a.g);this.C=ld(a.G);this.j=ld(a.H);this.u=a.F;Zb(a.s,function(b){if(!Hc(b,"data-"))throw new Rb('Only "data-" attributes allowed, got: %s.',[b]);if(Hc(b,"data-sanitizer-"))throw new Rb('Attributes with "%s" prefix are not allowed, got: %s.',["data-sanitizer-",b]);this.g["* "+b.toUpperCase()]=yi},
this);Zb(a.m,function(b){b=b.toUpperCase();if(-1==b.indexOf("-")||vi[b])throw new Rb("Only valid custom element tag names allowed, got: %s.",[b]);this.j[b]=!0},this);this.s=a.j;this.l=a.D;this.h=null;this.m=a.u};w(zi,si);
var Ai=function(a){return function(b,c){return(b=a(Kc(b),c))&&"about:invalid#zClosurez"!=ae(b)?ae(b):null}},wi=function(){this.g={};Zb([qh,rh],function(a){Zb(gd(a),function(b){this.g[b]=yi},this)},this);this.h={};this.s=[];this.m=[];this.G=ld(ti);this.H=ld(ui);this.F=!1;this.N=fe;this.V=this.C=this.K=this.j=zd;this.D=null;this.l=this.u=!1},Bi=function(a,b){return function(c,d,e,f){c=a(c,d,e,f);return null==c?null:b(c,d,e,f)}},Ci=function(a,b,c,d){a[c]&&!b[c]&&(a[c]=Bi(a[c],d))};wi.prototype.ja=function(){return new zi(this)};
var xi=function(a){if(a.l)throw Error("HtmlSanitizer.Builder.build() can only be used once.");Ci(a.g,a.h,"* USEMAP",Di);var b=Ai(a.N);Zb(["* ACTION","* CITE","* HREF"],function(d){Ci(this.g,this.h,d,b)},a);var c=Ai(a.j);Zb(["* LONGDESC","* SRC","LINK HREF"],function(d){Ci(this.g,this.h,d,c)},a);Zb(["* FOR","* HEADERS","* NAME"],function(d){Ci(this.g,this.h,d,Ya(Ei,this.K))},a);Ci(a.g,a.h,"A TARGET",Ya(Fi,["_blank","_self"]));Ci(a.g,a.h,"* CLASS",Ya(Gi,a.C));Ci(a.g,a.h,"* ID",Ya(Hi,a.C));Ci(a.g,a.h,
"* STYLE",Ya(a.V,c));a.l=!0},Ii=function(a,b){a||(a="*");return(a+" "+b).toUpperCase()},yi=function(a){return Kc(a)},Fi=function(a,b){b=Kc(b);return ic(a,b.toLowerCase())?b:null},Di=function(a){return(a=Kc(a))&&"#"==a.charAt(0)?a:null},Ei=function(a,b,c){return a(Kc(b),c)},Gi=function(a,b,c){b=b.split(/(?:\s+)/);for(var d=[],e=0;e<b.length;e++){var f=a(b[e],c);f&&d.push(f)}return 0==d.length?null:d.join(" ")},Hi=function(a,b,c){return a(Kc(b),c)},Ji=function(a,b){var c=b.data;(b=$h(b))&&"style"==
Yh(b).toLowerCase()&&!("STYLE"in a.C)&&"STYLE"in a.j&&(c=ve(ii(c,a.h,Xa(function(d,e){return this.s(d,{jP:e})},a))));return document.createTextNode(c)},Ki=function(a){var b=(new wi).ja();var c=!("STYLE"in b.C)&&"STYLE"in b.j;c="*"==b.l&&c?"sanitizer-"+Ne():b.l;b.h=c;if(qi){c=a;if(qi){a=Kf(document,"SPAN");b.h&&"*"==b.l&&(a.id=b.h);b.m&&(c=hi("<div>"+c+"</div>"),li(c),c=c.innerHTML);c=Be(c,null);var d=document.createElement("template");if(ri&&"content"in d)Ge(d,c),d=d.content;else{var e=document.implementation.createHTMLDocument("x");
d=e.body;Ge(e.body,c)}c=document.createTreeWalker(d,NodeFilter.SHOW_ELEMENT|NodeFilter.SHOW_TEXT,null,!1);for(d=mi?new WeakMap:new oi;e=c.nextNode();){c:{var f=b;var g=e;var h=Zh(g);switch(h){case 3:g=Ji(f,g);break c;case 1:h=g;1==Zh(h)||Vb("Expected Node of type Element but got Node of type %s",Zh(h));g=f;f=h;if("TEMPLATE"==Yh(f).toUpperCase())g=null;else{h=Yh(f).toUpperCase();if(h in g.C)var l=null;else g.j[h]?l=document.createElement(h):(l=Kf(document,"SPAN"),g.u&&Uh(l,"data-sanitizer-original-tag",
h.toLowerCase()));if(l){var q=l,r=Th(f);if(null!=r)for(var y=0;h=r[y];y++)if(h.specified){var D=g;var A=f,K=h,P=K.name;if(Hc(P,"data-sanitizer-"))D=null;else{var ha=Yh(A);K=K.value;var ob={tagName:Kc(ha).toLowerCase(),attributeName:Kc(P).toLowerCase()},wb={iu:void 0};"style"==ob.attributeName&&(wb.iu=Vh(A));A=Ii(ha,P);A in D.g?(D=D.g[A],D=D(K,ob,wb)):(P=Ii(null,P),P in D.g?(D=D.g[P],D=D(K,ob,wb)):D=null)}null!==D&&Uh(q,h.name,D)}g=l}else g=null}break c;default:Dg(pi,"Dropping unknown node type: "+
h),g=null}}if(g){if(1==Zh(g)&&d.set(e,g),e=$h(e),f=!1,e)h=Zh(e),l=Yh(e).toLowerCase(),q=$h(e),11!=h||q?"body"==l&&q&&(h=$h(q))&&!$h(h)&&(f=!0):f=!0,h=null,f||!e?h=a:1==Zh(e)&&(h=d.get(e)),h.content&&(h=h.content),h.appendChild(g)}else Lf(e)}d.clear&&d.clear();b=a}else b=Kf(document,"SPAN");0<Th(b).length&&(a=Kf(document,"SPAN"),a.appendChild(b),b=a);b=(new XMLSerializer).serializeToString(b);b=b.slice(b.indexOf(">")+1,b.lastIndexOf("</"))}else b="";return Be(b,null)};if("undefined"!=typeof angular){var Li=angular.module("chrome_18n",[]);chrome.runtime&&chrome.runtime.getManifest&&chrome.runtime.getManifest().default_locale&&Li.directive("angularMessage",function(){return{restrict:"E",replace:!0,controller:["$scope",function(a){var b=this;this.bk=this.ih=null;a.dirForText=function(c){b.ih||(b.ih=chrome.i18n.getMessage("@@bidi_dir")||"ltr");b.bk||(b.bk=new Gg("rtl"==b.ih));var d=b.bk,e,f=e=0,g=!1;c=(c||"").split(Qd);for(var h=0;h<c.length;h++){var l=c[h];Od.test(l)?
(e++,f++):Pd.test(l)?g=!0:Nd.test(l)?f++:Rd.test(l)&&(g=!0)}e=0==f?g?1:0:.4<e/f?-1:1;return-1==(0==e?d.g:e)?"rtl":"ltr"}}],compile:function(a,b){b=b.key;var c=null,d=document.createElement("amr");b&&!b.match(/^\d+$/)&&(b=chrome.i18n.getMessage(b),null==b&&d.setAttribute("id","missing"));if(b){var e=chrome.i18n.getMessage(b+"_ph");c=[];if(null!=e)for(c=e.split("\ue000"),e=0;e<c.length;++e)c[e]=c[e].replace(/^{{(.*)}}$/,'<amrp dir="{{dirForText($1)}}">{{$1}}</amrp>');c=chrome.i18n.getMessage(b,c)}else d.setAttribute("r",
"nokey");c?He(d,Ki(c)):(d.setAttribute("tl","false"),He(d,Ki(a.html())));a.replaceWith(d)}}})};var Ni=function(a,b){var c=this;this.m=b;this.g=a;this.g.top=a;this.s=[];this.l=!1;this.h=new Lg;this.g.videoSmoothnessRatings=this.wm(Wg,Rg,Sg,Tg,Ug,Vg);this.g.videoQualityRatings=this.wm(Wg,Xg,Yg,Zg,$g,ah);this.g.audioQualityRatings=this.wm(Wg,bh,ch,dh,eh,fh);this.s=[{value:"Bug",desc:Mg},{value:"FeatureRequest",desc:Ng},{value:"MirroringQuality",desc:Og},{value:"Discovery",desc:Pg},{value:"Other",desc:Qg}];this.g.feedbackTypes=this.s;this.g.includeFineLogs=!0;this.g.feedbackType="Bug";this.g.sendFeedback=
this.Az.bind(this);this.g.cancel=this.Yt.bind(this);this.g.attachLogsClick=this.C.bind(this);this.g.viewLogs=this.D.bind(this);this.g.$watchGroup("videoSmoothness videoQuality audioQuality feedbackDescription comments feedbackType".split(" "),this.cu.bind(this));this.g.sufficientFeedback=!1;this.g.$watch("attachLogs",this.C.bind(this));this.g.attachLogs=!0;this.u=Ne();this.g.userEmail="";chrome.identity.getProfileUserInfo(function(d){c.g.userEmail=d.email;Mi(c)});this.g.yourAnswerText=ph;this.g.language=
chrome.i18n&&chrome.i18n.getUILanguage?chrome.i18n.getUILanguage():chrome.runtime.getManifest().default_locale;this.g.requestLogsInProgress=!1;this.g.mrVersion=chrome.runtime.getManifest().version};k=Ni.prototype;k.wm=function(a){for(var b=[],c=1;c<arguments.length;c++)b.push(new Oi(c,arguments[c]));b.push(new Oi(0,arguments[0]));return b};k.Yt=function(){this.g.feedbackDescription&&!confirm(gh)||window.close()};
k.cu=function(){var a=this.g.feedbackType;this.g.sufficientFeedback="MirroringQuality"==a?this.g.videoSmoothness||this.g.videoQuality||this.g.audioQuality||this.g.comments:"Discovery"==a?this.g.visibleInSetup||this.g.comments:!!this.g.feedbackDescription};
k.Az=function(){if(this.g.sufficientFeedback){var a=this.g.feedbackType,b="";"MirroringQuality"==a?(this.g.videoSmoothness&&(b+="\nVideo Smoothness: "+this.g.videoSmoothness),this.g.videoQuality&&(b+="\nVideo Quality: "+this.g.videoQuality),this.g.audioQuality&&(b+="\nAudio: "+this.g.audioQuality),this.g.projectedContentUrl&&(b+="\nProjected Content/URL: "+this.g.projectedContentUrl),this.g.comments&&(b+="\nComments: "+this.g.comments)):"Discovery"==a?(this.g.visibleInSetup&&(b+="\nChromecast Visible in Setup: "+
this.g.visibleInSetup),this.g.hasNetworkSoftware&&(b+="\nUsing VPN/proxy/firewall/NAS Software: "+this.g.hasNetworkSoftware),this.g.networkDescription&&(b+="\nNetwork Description: "+this.g.networkDescription),this.g.comments&&(b+="\nComments: "+this.g.comments)):b=this.g.feedbackDescription;a="Type: "+a+"\n\n"+b;this.g.sendDialogText=hh;this.g.okButton=oh;this.g.feedbackSent=!1;this.m.show({locals:{sP:this.g.feedbackSent,fQ:this.g.sendDialogText,Kx:this.g.okButton},scope:this.g,preserveScope:!0,bindToController:!0,
template:'<md-dialog id="feedback-confirmation"><md-dialog-content><div id="send-feedback-text">{{sendDialogText}}</div><md-dialog-actions><md-button class="md-raised md-primary"ng-disabled="!feedbackSent" ng-click="closeWindow()">{{okButton}}</md-button></md-dialog-actions></md-dialog-content></md-dialog>',controller:this.j});this.tq(a,Date.now())}};k.tq=function(a,b){var c=Date.now();!this.g.requestLogsInProgress||5E3<c-b?Pi(this,a):setTimeout(this.tq.bind(this),1E3,a,b)};
var Pi=function(a,b){var c=0,d=function(f,g,h){h?f(!0):(a.g.sendDialogText=kh,Mi(a),g(Error("Failed to send")))},e=chrome.declarativeWebRequest?"MrTeamfood":"MRStable";(new Ig(function(){c++;return new Promise(function(f,g){var h=a.g.userEmail,l=a.h;f=d.bind(null,f,g);g=chrome.runtime.getManifest();Kg({productId:85561,bucket:e,flow:"submit",serverUri:"https://www.google.com/tools/feedback",allowNonLoggedInFeedback:!0,locale:g.default_locale,enableAnonymousFeedback:!h,report:{description:b},callback:f},
{version:g.version,description:g.description,user_email:h||"NA",logs:l.Uc||"NA",external_logs:l.g||"NA",device_model:l.modelName||"NA",receiver_version:l.u||"NA",dash_report_url:l.l||"NA",cast_device_counts:l.h,dial_device_counts:l.j,mirroring_service_enabled:l.C,native_cast_mrp_enabled:l.m,native_dial_mrp_enabled:l.s})})},1E4,4)).start().then(function(){Jb("MediaRouter.Ui.Action.Feedback");a.g.sendDialogText=jh;a.g.feedbackSent=!0;Mi(a)},function(){a.g.sendDialogText=ih;a.g.feedbackSent=!0;Mi(a)})};
Ni.prototype.C=function(){var a=this;this.h=new Lg;this.g.attachLogs&&(this.g.requestLogsInProgress=!0,chrome.runtime.sendMessage(new Hg(this.u,"retrieve_log_data"),function(b){a.g.requestLogsInProgress=!1;a.h.Uc=b.logs||"no extension";a.h.Uc+="\n";a.h.Uc+=b.mediaSinkServiceStatus||"no media sink service status from browser";a.h.Uc+="\n";a.h.Uc+=b.mediaRouterLogs||"no Media Router logs from the browser";b.castStreamingLogs&&(a.h.l=b.castStreamingLogs);b.castDeviceCounts&&(a.h.h=b.castDeviceCounts);
b.dialDeviceCounts&&(a.h.j=b.dialDeviceCounts);a.h.C=!!b.mirroringServiceEnabled;a.h.m=!!b.nativeCastMrpEnabled;a.h.s=!!b.nativeDialMrpEnabled;if(b=b.device)if(b.model&&(a.h.modelName=b.model),b.version&&(a.h.u=b.version),!a.l){var c=Ne();a.l=!0;a.h.g=vb(b.ip,c,a.F.bind(a))}}))};
Ni.prototype.D=function(){this.g.logs=this.h.Uc;this.g.logsHeader=lh;this.g.sendLogs=mh;this.g.fineLogsWarning=nh;this.g.okButton=oh;this.m.show({locals:{dP:this.g.attachLogs,Uc:this.g.logs,CP:this.g.includeFineLogs,SP:this.g.logsHeader,gQ:this.g.sendLogs,uP:this.g.fineLogsWarning,Kx:this.g.okButton},scope:this.g,preserveScope:!0,bindToController:!0,clickOutsideToClose:!0,template:'<md-dialog><md-dialog-content id="logs-dialog"><div class="subheading">{{logsHeader}}</div><div ng-show="includeFineLogs && attachLogs"id="feedback-fine-log-warning" class="informative">{{fineLogsWarning}}</div><pre>{{logs}}</pre><div class="send-logs"><md-checkbox type="checkbox" ng-model="attachLogs"ng-change="attachLogsClick()"><span>{{sendLogs}}</span></md-checkbox></div><md-dialog-actions><md-button class="md-raised md-primary"ng-click="closeDialog()">{{okButton}}</md-button></md-dialog-actions></md-dialog-content></md-dialog>',
controller:this.j})};Ni.prototype.F=function(a,b){this.l=!1;this.h.g="error"==a?"":b;this.g.attachLogs||(this.h.g="");Mi(this)};var Mi=function(a){a.g.$$phase||a.g.$apply()};Ni.prototype.j=function(a,b){a.closeWindow=function(){window.close()};a.closeDialog=function(){b.hide()}};Ni.prototype.j.$inject=["$scope","$mdDialog"];var Oi=function(a,b){this.id=a;this.desc=b;this.text=0==a?b:a+" ("+b+")"};
angular.module("feedbackApp","chrome_18n material.components.button material.components.checkbox material.components.dialog material.components.input material.components.radioButton".split(" ")).controller("FeedbackCtrl",["$scope","$mdDialog",Ni]);v("ng.safehtml.googSceHelper.isGoogHtmlType",function(a){return a&&a.Pd?!0:!1});v("ng.safehtml.googSceHelper.isCOMPILED",function(){return!0});v("ng.safehtml.googSceHelper.unwrapAny",function(a){if(a instanceof Td)return Ud(a).toString();if(a instanceof ze)return Ae(a).toString();if(a instanceof $d)return ae(a);if(a instanceof he)return ie(a);if(a instanceof Ld)return Md(a).toString();throw Error();});
v("ng.safehtml.googSceHelper.unwrapGivenContext",function(a,b){if("html"==a)return Ae(b).toString();if("resourceUrl"==a||"templateUrl"==a)return Ud(b).toString();if("url"==a)return b instanceof Td?Ud(b).toString():ae(b);if("css"==a)return ie(b);if("js"==a)return Md(b).toString();throw Error();});
