'use strict';var Tx={TAB:0,Rm:1,Ds:2},Ux=function(){return new Ab("MediaRouter.CastStreaming.Session.Launch")},Vx=function(){return new Gb("MediaRouter.CastStreaming.Session.Length")},Wx=function(a){Kb("MediaRouter.CastStreaming.Start.Success",a,Tx)};var Xx=db("mr.mirror.cast.LogUploader"),Zx=function(a,b,c){Yx("raw_events.log.gz",a,b,c);return b?"https://crash.corp.google.com/samples?reportid=&q="+encodeURIComponent("UserComments='"+b+"'"):""},Yx=function(a,b,c,d){if(0==b.size)Xx.info("Trying to upload an empty file to Crash"),d&&d(null);else{var e=new FormData;e.append("prod","Cast");e.append("ver",chrome.runtime.getManifest().version);e.append(a,b);c&&e.append("comments",c);Ax("https://clients2.google.com/cr/report",function(f){f=f.target;
var g=null;Kx(f)?(g=Mx(f),Xx.info("Upload to Crash succeeded: "+g)):Xx.info("Upload to Crash failed. HTTP status: "+f.Ja());d&&d(g)},"POST",e,void 0,3E4)}};var $x=function(){this.g=0;fm(this)},by=function(){ay||(ay=new $x);return ay},cy=function(){var a=by(),b={fraction:.01,autoSubmitTimeLimitMillis:6048E5},c=b.autoSubmitTimeLimitMillis,d=Date.now();return a.g&&c&&d-a.g<c?!1:Math.random()<b.fraction};$x.prototype.ab=function(){return"mirror.cast.LogUtils"};$x.prototype.Vb=function(){return[void 0,{lastAutoSubmitMillis:this.g}]};$x.prototype.Tb=function(){var a=dm(this);this.g=a&&a.lastAutoSubmitMillis||0};var ay=null;db("mr.mirror.cast.LogUtils");var dy={NI:"OFFER",ZA:"ANSWER",IJ:"PRESENTATION",dF:"GET_STATUS",AM:"STATUS_RESPONSE",YE:"GET_CAPABILITIES",zC:"CAPABILITIES_RESPONSE",AL:"RPC"};var ey=function(){this.capabilities=this.status=this.g=this.error=this.rpc=this.result=this.type=this.h=this.sessionId=null},hy=function(a){try{if("string"!==typeof a)throw SyntaxError("Cannot parse non-string as JSON");var b;fy(JSON.parse(a),function(d){b=gy(d)},function(){throw Error("non-Object result from JSON parse");});return b}catch(d){var c=d instanceof SyntaxError?"JSON parse error: "+d.message:"Type coercion error: "+d.message}"string"==typeof a?a="a string: "+a:a instanceof ArrayBuffer?
(a=new Uint8Array(a),a="an ArrayBuffer whose base64 is "+btoa(String.fromCharCode.apply(null,a))):a="of invalid data type "+typeof a;throw Error(c+". Input was "+a);},gy=function(a){var b=new ey;null!=a.sessionId&&(b.sessionId=String(a.sessionId));iy(a.seqNum,function(f){b.h=f},function(){throw Error('"seqNum" must be a number');});if("type"in a){for(var c=String(a.type).toUpperCase(),d=n(Object.keys(dy)),e=d.next();!e.done;e=d.next())if(dy[e.value]==c){b.type=c;break}if(!b.type)throw Error('not a known message "type"');
}"result"in a&&(b.result=String(a.result));if("rpc"in a){if("string"!==typeof a.rpc)throw Error('"rpc" must be a String containing a base64 payload');b.rpc=new Uint8Array([].concat(p(atob(a.rpc))).map(function(f){return f.charCodeAt(0)}))}fy(a.error,function(f){b.error=jy(f)},function(){throw Error('"error" must be an Object');});fy(a.answer,function(f){b.g=ky(f)},function(){throw Error('"answer" must be an Object');});fy(a.status,function(f){b.status=ly(f)},function(){throw Error('"status" must be an Object');
});fy(a.capabilities,function(f){b.capabilities=my(f)},function(){throw Error('"capabilities" must be an Object');});return b},fy=function(a,b,c){void 0!==a&&(a instanceof Object?b(a):c())},iy=function(a,b,c){void 0!==a&&("number"!==typeof a?c():b(a))},ny=function(a,b,c){void 0!==a&&(a instanceof Array&&a.every(function(d){return"number"===typeof d})?b(a):c())},oy=function(a,b,c){void 0!==a&&(a instanceof Array?b(a.map(function(d){return String(d)})):c())},py=function(){this.C=null;this.g=[];this.h=
[];this.j=this.l=this.m=null},ky=function(a){var b=new py;iy(a.udpPort,function(c){b.C=c},function(){throw Error('"answer.udpPort" must be a number');});ny(a.sendIndexes,function(c){b.g=c},function(){throw Error('"answer.sendIndexes" must be an array of numbers');});ny(a.ssrcs,function(c){b.h=c},function(){throw Error('"answer.ssrcs" must be an array of numbers');});"IV"in a&&(b.m=String(a.IV));"receiverGetStatus"in a&&(b.l="true"==String(a.receiverGetStatus).toLowerCase());"castMode"in a&&(b.j=String(a.castMode));
return b},qy=function(){this.details=this.description=this.code=null},jy=function(a){var b=new qy;iy(a.code,function(c){b.code=c},function(){throw Error('"error.code" must be a number');});"description"in a&&(b.description=String(a.description));fy(a.details,function(c){b.details=c},function(){throw Error('"error.details" must be an Object');});return b},ry=function(){this.h=this.g=null},ly=function(a){var b=new ry;iy(a.wifiSnr,function(c){b.g=c},function(){throw Error('"status.wifiSnr" must be a number');
});ny(a.wifiSpeed,function(c){b.h=c},function(){throw Error('"status.wifiSpeed" must be an array of numbers');});return b},sy=function(){this.h=this.g=null},my=function(a){var b=new sy;oy(a.mediaCaps,function(c){b.g=c},function(){throw Error('"capabilities.mediaCaps" must be an array');});if("keySystems"in a){a=a.keySystems;if(!(a instanceof Array))throw Error('"capabilities.keySystems" must be an array');b.h=a.map(function(c){var d;fy(c,function(e){d=ty(e)},function(){throw Error('"capabilities.keySystems" entries must be *Objects');
});return d})}return b},uy=function(){this.h=this.m=this.C=this.l=this.u=this.g=this.s=this.codecs=this.initDataTypes=this.j=null},ty=function(a){var b=new uy;"keySystemName"in a&&(b.j=String(a.keySystemName));oy(a.initDataTypes,function(c){b.initDataTypes=c},function(){throw Error('"capabilities.initDataTypes" must be an array');});oy(a.codecs,function(c){b.codecs=c},function(){throw Error('"capabilities.codecs" must be an array');});oy(a.secureCodecs,function(c){b.s=c},function(){throw Error('"capabilities.secureCodecs" must be an array');
});oy(a.audioRobustness,function(c){b.g=c},function(){throw Error('"capabilities.audioRobustness" must be an array');});oy(a.videoRobustness,function(c){b.u=c},function(){throw Error('"capabilities.videoRobustness" must be an array');});"persistentLicenseSessionSupport"in a&&(b.l=String(a.persistentLicenseSessionSupport));"persistentReleaseMessageSessionSupport"in a&&(b.C=String(a.persistentReleaseMessageSessionSupport));"persistentStateSupport"in a&&(b.m=String(a.persistentStateSupport));"distinctiveIdentifierSupport"in
a&&(b.h=String(a.distinctiveIdentifierSupport));return b};var vy=function(a){this.o=db("mr.mirror.cast.MessageDispatcher");this.l=a;this.g=null;this.h=new Map;this.j=0},wy=function(a,b,c){if(a.h.has(b))throw Error("Attempt to multiple-subscribe to the same response type: "+b);a.h.set(b,c);a.j=0;kb(a.o,"Added subscriber for "+b+"-type messages.");a.g||(a.g=lw(a.l),a.g.onMessage=a.C.bind(a))},xy=function(a,b){a.h.delete(b)&&kb(a.o,function(){return"Removed subscriber of "+b+"-type messages."});0==a.h.size&&a.g&&(a.g.dispose(),a.g=null)};
vy.prototype.sendMessage=function(a){return this.g?"RPC"==a.type?this.g.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.remoting"}):this.g.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.webrtc"}):Promise.reject(Error("Require at least one subscriber before sending messages."))};
var yy=function(a,b,c,d,e){var f=null,g=function(){xy(a,c);null!=f&&(clearTimeout(f),f=null)};try{wy(a,c,function(h){e(h)&&g()})}catch(h){e(null,h);return}f=setTimeout(function(){g();e(null,Error("timeout"))},d);a.sendMessage(b).catch(function(h){g();e(null,h)})};
vy.prototype.C=function(a){if(a&&"string"===typeof a.namespace_&&a.namespace_.startsWith("urn:x-cast:com.google.cast.")){do{var b=void 0;try{b=hy(a.data)}catch(d){b=d.message;break}if(b.type){var c=this.h.get(b.type);if(c)try{c(b);return}catch(d){b="Error thrown during delivery. Response was: "+(JSON.stringify(b)+". Error from subscriber callback was: ")+(d.message+".")}else b="Message was ignored: "+JSON.stringify(b)}else b="Message did not include response type: "+JSON.stringify(b)}while(0);10>
this.j?this.o.L(b):kb(this.o,b);++this.j}};var zy=function(){this.g=Promise.resolve(1)},By=function(a,b,c){return Ay(a,function(d){return d==b},c)},Cy=function(a,b){var c=[3,4];return Ay(a,function(d){return-1!=c.indexOf(d)},b)},Dy=function(a,b){a.g=a.g.catch(function(){return 1});return Ay(a,function(){return!0},b)},Ay=function(a,b,c){var d,e,f=new Promise(function(g,h){d=g;e=h});a.g=a.g.then(function(g){if(!b(g))return e(Error("Operation requires a different starting checkpoint than "+g)),Promise.resolve(g);var h=new Ey(g);try{var l=c(h)}catch(q){l=
Promise.reject(q)}return l.then(function(q){return d(q)},function(q){return e(q)}).then(function(){if(null===h.g)throw Error("A prior operation that started at "+(g+" did not complete."));return h.g})},function(g){e(g);throw g;});return f},Ey=function(a){this.h=a;this.g=null},Fy=function(a,b){a.g="number"===typeof b?b:a.h};var Gy=chrome.cast.streaming,Hy=db("mr.mirror.cast.StreamingLaunchWorkflow"),Jy=function(a,b,c,d,e){this.N=a.sessionId;this.F=a.Uh;this.X=a.Se;this.j=b;this.V=c;this.K=d;this.Z=Iy(e,"onAnswer",this.F);this.xb=Iy(e,"onSessionStop",this.F);this.o=Hy;this.D=new zy;this.s=this.G=this.u=this.h=this.g=this.m=this.C=this.l=null};
Jy.prototype.start=function(a,b,c){var d=this;if(!a&&!b)return Promise.reject(Error("No tracks to stream"));var e=a instanceof Ky,f=b instanceof Ky;(e&&b&&!f||f&&a&&!e)&&Vb("Mixing remoting and non-remoting tracks");return By(this.D,1,function(g){d.l=a;d.C=b;d.m=c;d.o.info(function(){return"Launching streaming for "+Ly(d)+" to a "+(d.X+".")});return My(d).then(d.H.bind(d)).then(function(h){return Ny(d,h).then(function(l){d.Z();var q=Oy(d,l,h);d.g=Py(d,d.g,q);d.h=Py(d,d.h,q);if(!d.g&&!d.h)throw Error("Receiver did not select any offers from: "+
JSON.stringify(h));d.G=!!l.l;d.s=function(r,y){r==d.g?d.m.Jf("Audio stream (id="+r+") error: "+y):r==d.h&&d.m.Jf("Video stream (id="+r+") error: "+y)};Gy.rtpStream.onError.addListener(d.s);return Qy(d,l,q)})}).then(function(){d.o.info(function(){return"Launched streaming for "+Ly(d)});d.m.hh(d);Fy(g,2);return{Mt:d.g,wA:d.h}})})};
Jy.prototype.stop=function(){var a=this;return Dy(this.D,function(b){if(!a.l&&!a.C)return Fy(b,1),Promise.resolve();a.o.info(function(){return"Stopping streaming for "+Ly(a)+"."});a.s&&(Gy.rtpStream.onError.removeListener(a.s),a.s=null);if(a.m){var c=a.m.Yh();a.m=null}else c=Promise.resolve();return c.then(function(){a.g&&(Gy.rtpStream.stop(a.g),Gy.rtpStream.destroy(a.g),a.g=null);a.h&&(Gy.rtpStream.stop(a.h),Gy.rtpStream.destroy(a.h),a.h=null);a.u&&(Gy.udpTransport.destroy(a.u),a.u=null);a.xb();
a.o.info(function(){return"Stopped streaming for "+Ly(a)+"."});a.l=null;a.C=null;Fy(b,1)})})};
var Ry=function(a,b){var c=JSON.stringify(b);return Promise.all([a.g&&new Promise(function(d){return Gy.rtpStream.getRawEvents(a.g,c,d)}),a.h&&new Promise(function(d){return Gy.rtpStream.getRawEvents(a.h,c,d)})]).catch(function(d){a.o.error("Unexpected error when calling getRawEvents()",d);return[]}).then(function(d){return new Blob(d.filter(function(e){return!!e}),{type:"application/gzip"})})},Sy=function(a){return Promise.all([a.g&&new Promise(function(b){return Gy.rtpStream.getStats(a.g,b)}),a.h&&
new Promise(function(b){return Gy.rtpStream.getStats(a.h,b)})]).catch(function(b){a.o.error("Unexpected error when calling getStats()",b);return[]}).then(function(b){return Object.assign.apply(Object,[{}].concat(p(b.filter(function(c){return!!c}))))})},Ly=function(a){if(a.l&&a.C)var b="audio+video ";else if(a.l)b="audio-only ";else if(a.C)b="video-only ";else return"stopped";return a.l instanceof Ky||a.C instanceof Ky?b+"remoting":b+"streaming"},My=function(a){return new Promise(function(b){var c=
function(d,e,f){d&&!a.l&&(Gy.rtpStream.destroy(d),d=null);e&&!a.C&&(Gy.rtpStream.destroy(e),e=null);a.o.info(function(){return"Created Cast Streaming session: audioStreamId="+d+", videoStreamId="+e+"."});a.g=d;a.h=e;a.u=f;b()};a.l instanceof Ky||a.C instanceof Ky?Gy.session.create(null,null,c):Gy.session.create(a.l,a.C,c)})};
Jy.prototype.H=function(){for(var a=Yj(),b=Yj(),c=[],d=n([this.g,this.h]),e=d.next();!e.done;e=d.next())if(e=e.value)for(var f=e==this.g,g=f?127:96,h=f?Math.floor(499999*Math.random())+1:Math.floor(499999*Math.random())+500001,l=f?48E3:9E4,q=n(Gy.rtpStream.getSupportedParams(e)),r=q.next();!r.done;r=q.next())r=r.value,r.payload.payloadType=g,r.payload.maxLatency=this.j.maxLatencyMillis,r.payload.minLatency=this.j.minLatencyMillis,r.payload.animatedLatency=this.j.animatedLatencyMillis,r.payload.ssrc=
h,r.payload.clockRate=l,r.payload.aesKey=a,r.payload.aesIvMask=b,f?(r.payload.channels=2,r.payload.maxBitrate=this.j.audioBitrate,r.payload.maxFrameRate=100):(r.payload.minBitrate=this.j.minVideoBitrate,r.payload.maxBitrate=this.j.maxVideoBitrate,r.payload.maxFrameRate=this.j.maxFrameRate),c.push(new Ty(e,r));return c};
var Py=function(a,b,c){b&&!c.some(function(d){return d.streamId==b})&&(a.o.L("Destroying RTP stream not selected by the receiver: id="+b),Gy.rtpStream.destroy(b),b=null);return b},Ny=function(a,b){return new Promise(function(c,d){for(var e=[],f=0;f<b.length;++f){var g=b[f].params,h={index:f,codecName:g.payload.codecName.toLowerCase(),rtpProfile:"cast",rtpPayloadType:g.payload.payloadType,ssrc:g.payload.ssrc,targetDelay:g.payload.animatedLatency,aesKey:g.payload.aesKey,aesIvMask:g.payload.aesIvMask,
timeBase:"1/"+g.payload.clockRate,receiverRtcpEventLog:a.j.enableLogging,rtpExtensions:["adaptive_playout_delay"]};a.j.dscpEnabled&&(h.receiverRtcpDscp=46);127==g.payload.payloadType?Object.assign(h,{type:"audio_source",bitRate:0<g.payload.maxBitrate?1E3*g.payload.maxBitrate:60*g.payload.maxFrameRate+g.payload.clockRate*g.payload.channels,sampleRate:g.payload.clockRate,channels:g.payload.channels}):Object.assign(h,{type:"video_source",renderMode:"video",maxFrameRate:Math.round(1E3*g.payload.maxFrameRate)+
"/1000",maxBitRate:1E3*g.payload.maxBitrate,resolutions:[{width:a.j.maxWidth,height:a.j.maxHeight}]});e.push(h)}var l=a.l instanceof Ky||a.C instanceof Ky?"remoting":"mirroring",q={type:"OFFER",sessionId:a.N,seqNum:qn(a.V),offer:{castMode:l,receiverGetStatus:!0,supportedStreams:e}};a.o.info(function(){return"Sending OFFER message: "+JSON.stringify(q)});yy(a.K,q,"ANSWER",1E4,function(r,y){if(null==r)d(y);else if("ok"==r.result&&r.g){if(r.h!=q.seqNum)return a.o.L("Ignoring ANSWER for OFFER with different seqNum: "+
JSON.stringify(r)),!1;((y=r.g.j)&&y!=l||!y&&"mirroring"!=l)&&a.o.error("Expected receiver to ANSWER with castMode="+l+", but got: "+y);kb(a.o,function(){return"Received ANSWER: "+JSON.stringify(r)});c(r.g)}else d(Error("Non-OK ANSWER received: "+JSON.stringify(r)));return!0})})},Oy=function(a,b,c){if(b.g.length!=b.h.length)return a.o.error("sendIndexes.length != ssrcs.length in ANSWER: "+JSON.stringify(b)),[];for(var d=[],e={},f=0;f<b.g.length;e={Tf:e.Tf},++f){var g=b.g[f];if(0>g||g>=c.length)return a.o.error("Receiver selected invalid index ("+
g+" < "+c.length+") in ANSWER: "+JSON.stringify(b)),[];e.Tf=c[g];if(d.some(function(h){return function(l){return l.streamId==h.Tf.streamId}}(e)))return a.o.error("Receiver selected same RTP stream twice in ANSWER: "+JSON.stringify(b)),[];e.Tf.params.payload.feedbackSsrc=b.h[g];if(d.some(function(h){return function(l){return l.params.payload.feedbackSsrc==h.Tf.params.payload.feedbackSsrc}}(e)))return a.o.error("Receiver provided same SSRC for two different RTP streams in ANSWER: "+JSON.stringify(b)),
[];d.push(e.Tf)}return d},Qy=function(a,b,c){var d=null,e=function(){d&&(Gy.rtpStream.onStarted.removeListener(d),d=null)};return(new Promise(function(f,g){var h=b.C||2344;a.o.info(function(){return"Starting RTP streams to receiver at "+(a.F+":"+h)+(" for selected offers: "+JSON.stringify(c))});var l=a.u||-1;a.j.dscpEnabled&&(a.o.info("Enabled DSCP in sender."),Gy.udpTransport.setOptions(l,{DSCP:!0}));Gy.udpTransport.setDestination(l,{address:a.F,port:h});var q=new Set(c.map(function(y){return y.streamId}));
d=function(y){q.delete(y);0==q.size&&f()};Gy.rtpStream.onStarted.addListener(d);l=n(c);for(var r=l.next();!r.done;r=l.next())r=r.value,Gy.rtpStream.toggleLogging(r.streamId,a.j.enableLogging),Gy.rtpStream.start(r.streamId,r.params);setTimeout(function(){g(Error("Timeout: RTP streams failed to start."))},1E4)})).then(e).catch(function(f){e();throw f;})},Iy=function(a,b,c){return a&&b in a?function(){try{a[b](c)}catch(d){Hy.error("Error from testHooks."+b,d)}}:function(){}},Ty=function(a,b){this.streamId=
a;this.params=b},Ky=function(){};var Uy=db("mr.mirror.cast.MediaRemoter"),Xy=function(a,b,c,d,e,f){this.s=a;this.K=Vy(b,this.s.Cb);this.V=new Jy(this.s.Cb,c,d,e,f);this.G=e;this.C=new zy;this.j=new Wy;this.D=new mojo.Binding(mojo.MirrorServiceRemoter,this,null);this.o=Uy;this.F=this.g=this.m=this.l=this.H=null;this.h=!0;this.u=this.N.bind(this)},$y=function(a,b,c){return By(a.C,1,function(d){a.H=b;a.l=c;var e=a.D.createInterfacePtrAndBind();a.D.setConnectionErrorHandler(function(){a.o.info("Remoter mojo pipe connection error.");
Yy(a)});a.g=new mojo.MirrorServiceRemotingSourcePtr;var f=Kj(a.s.mediaSource||"");if(!f)throw Error("Failed to parse tab ID from source:\n          "+a.s.mediaSource);a.o.info("Connecting remoter to browser: tabId="+f);(tj.get("mr.ProviderManager")||null).onMediaRemoterCreated(f,e,mojo.makeRequest(a.g));a.g.ptr.setConnectionErrorHandler(function(){a.o.info("RemotingSource mojo pipe connection error.");Yy(a)});return Zy(a).then(function(){if(a.h)a.g.onSinkAvailable(a.K);Fy(d,2)})})},Yy=function(a){return Dy(a.C,
function(b){a.g&&(a.g.ptr.reset(),a.g=null);var c=a.m;a.m=null;a.l=null;a.H=null;a.D.close();chrome.settingsPrivate.onPrefsChanged.hasListener(a.u)&&chrome.settingsPrivate.onPrefsChanged.removeListener(a.u);return new Promise(function(d){window.setTimeout(function(){az(a).then(function(){Fy(b,1);d();c&&c()})},250)})})};k=Xy.prototype;k.Bz=function(a){bz(this.j,a)};k.hh=function(a){this.l&&this.l.hh(a)};k.Yh=function(){return this.l?this.l.Yh():Promise.resolve()};
k.Jf=function(a,b){this.o.error("Error during streaming: "+a,b);if(this.g)this.g.onError();Yy(this)};
k.start=function(){var a=this,b=!1;this.o.info(function(){b=!0;return"Starting next media remoting session."});b&&cz(this.j,function(c){return a.o.info(c)});dz(this.j);By(this.C,2,function(c){return(0,a.H)().then(function(d){a.m=d;wy(a.G,"RPC",function(e){if(e.rpc){var f=a.j;e=e.rpc;f.m&&(++f.s,f.h+=e.length,f.m(e))}});Fy(c,3)}).catch(function(d){return az(a).then(function(){Fy(c);throw d;})})}).then(function(){a.o.info("Remoting started successfully.")}).catch(function(c){a.o.error("Failed to start remoting",c);
a.g.onError()})};k.aA=function(a,b){var c=this;return By(this.C,3,function(d){return c.V.start(a?new Ky:null,b?new Ky:null,c).then(function(e){ez(c.j,function(f){return c.G.sendMessage(f)},function(f){c.g.onMessageFromSink(f)});Fy(d,4);return{audio_stream_id:e.Mt||-1,video_stream_id:e.wA||-1}}).catch(function(e){return az(c).then(function(){Fy(d);throw e;})})}).catch(function(d){c.o.error("Failed to start remoting streams",d);Yy(c);return{audio_stream_id:-1,video_stream_id:-1}})};
k.stop=function(a){var b=this;Cy(this.C,function(c){b.g.onStopped(a);return az(b).then(function(){b.o.info("Remoting stopped.");Fy(c,5);(0,b.m)().then(function(){return By(b.C,5,function(d){if(b.g&&b.h)b.g.onSinkAvailable(b.K);Fy(d,2);return Promise.resolve()})}).catch(function(d){throw d;});b.m=null})}).catch(function(c){b.o.error("Failed to stop remoting: ",c);Yy(b)})};
k.qu=function(){null===this.F&&(this.F=zb(this.s.Cb.Uh).then(function(a){return a.h||!1}));return this.F.then(function(a){return{rate:(a?1E7:5E6)/8}})};
var az=function(a){return a.V.stop().then(function(){xy(a.G,"RPC");fz(a.j);gz(a.j)})},Zy=function(a){return new Promise(function(b){chrome.settingsPrivate.getPref("media_router.media_remoting.enabled",function(c){chrome.runtime.lastError?a.o.error("Encountered error getting media remoting pref: "+JSON.stringify(chrome.runtime.lastError)):c.type!=chrome.settingsPrivate.PrefType.BOOLEAN?a.o.error("Pref value not a boolean: "+JSON.stringify(c)):(a.h=!!c.value,a.o.info("Initializing mediaRemotingEnabled_ with value read from pref: "+
a.h));chrome.settingsPrivate.onPrefsChanged.hasListener(a.u)||chrome.settingsPrivate.onPrefsChanged.addListener(a.u);b()})})};
Xy.prototype.N=function(a){if(this.g){a=n(a);for(var b=a.next();!b.done;b=a.next())if(b=b.value,"media_router.media_remoting.enabled"==b.key){if(b.type!=chrome.settingsPrivate.PrefType.BOOLEAN){this.o.error("Pref value not a boolean: "+JSON.stringify(b));break}a=!!b.value;if(this.h==a)break;this.h=a;this.o.info("mediaRemotingEnabled_ changed to: "+this.h);if(this.h)this.g.onSinkAvailable(this.K);else this.g.onStopped(mojo.RemotingStopReason.USER_DISABLED);break}}};
var Vy=function(a,b){var c=new mojo.RemotingSinkMetadata;c.features=[];c.friendly_name=b.Wz||"";c.audio_capabilities=[];c.video_capabilities=[];var d=mojo.RemotingSinkAudioCapability,e=mojo.RemotingSinkVideoCapability,f=c.audio_capabilities,g=c.video_capabilities,h=b.Se||"";(a.g||[]).forEach(function(l){switch(l){case "audio":f.push(d.CODEC_BASELINE_SET);break;case "aac":f.push(d.CODEC_AAC);break;case "opus":f.push(d.CODEC_OPUS);break;case "video":g.push(e.CODEC_BASELINE_SET);break;case "4k":g.push(e.SUPPORT_4K);
break;case "h264":g.push(e.CODEC_H264);break;case "vp8":g.push(e.CODEC_VP8);break;case "vp9":h.startsWith("Chromecast Ultra")&&g.push(e.CODEC_VP9);break;case "hevc":h.startsWith("Chromecast Ultra")&&g.push(e.CODEC_HEVC);break;default:Uy.info("Unknown mediaCap name: "+l)}});b.Se&&"Chromecast Ultra"==b.Se&&g.push(e.SUPPORT_4K);return c};Xy.prototype.estimateTransmissionCapacity=Xy.prototype.qu;Xy.prototype.stop=Xy.prototype.stop;Xy.prototype.startDataStreams=Xy.prototype.aA;Xy.prototype.start=Xy.prototype.start;
Xy.prototype.sendMessageToSink=Xy.prototype.Bz;
var Wy=function(){this.m=this.C=this.g=null;this.F=this.h=this.s=this.j=this.u=0;this.l=null},dz=function(a){a.g=[];hz(a,performance.now())},ez=function(a,b,c){a.C=b;a.m=c;a.g?(b=a.g,a.g=null,b.forEach(function(d){return bz(a,d.data).then(d.Dz,d.uq)})):hz(a,performance.now())},fz=function(a){if(a.g){var b=Error("Stop before delivering pending message");a.g.forEach(function(c){return c.uq(b)});a.g=null}a.C=null;a.m=null},bz=function(a,b){if(a.C){var c=btoa(String.fromCharCode.apply(null,b));++a.u;
a.j+=b.length;return a.C({type:"RPC",rpc:c})}return a.g?new Promise(function(d,e){a.g.push({data:b,Dz:d,uq:e})}):Promise.reject(Error("RPC pipe not started"))},cz=function(a,b){gz(a);a.l=setInterval(function(){if(a.g)var c=a.g.length+" messages are waiting to send.";else{c=performance.now();var d=(c-a.F)/1E3;d="Over the past "+d.toFixed(1)+" seconds, sent "+(a.u+" messages ("+Math.round(a.j/d)+" bytes/sec) and received ")+(a.s+" messages ("+Math.round(a.h/d)+" bytes/sec).");hz(a,c);c=d}b(c)},3E4)},
gz=function(a){null!=a.l&&(clearInterval(a.l),a.l=null)},hz=function(a,b){a.u=0;a.j=0;a.s=0;a.h=0;a.F=b};var iz=function(a){return a&&a.getAudioTracks()&&0<a.getAudioTracks().length?a.getAudioTracks()[0]:null},jz=function(a){return a&&a.getVideoTracks()&&0<a.getVideoTracks().length?a.getVideoTracks()[0]:null};var kz=function(a,b,c,d,e){this.j=new Jy(a,b,c,d,void 0===e?null:e);this.o=db("mr.mirror.cast.MediaStreamer");this.C=new zy;this.l=this.h=this.g=this.m=null};kz.prototype.start=function(a,b){var c=this;return By(this.C,1,function(d){c.m=a;c.g=iz(a);c.g&&"ended"==c.g.readyState&&(c.g=null);c.h=jz(a);c.h&&"ended"==c.h.readyState&&(c.h=null);if(!c.g&&!c.h)return Fy(d),Promise.reject(Error("No MediaStream tracks to stream."));c.l=b;return c.j.start(c.g,c.h,c.l).then(function(){return Fy(d,2)})})};
kz.prototype.stop=function(){var a=this;return Dy(this.C,function(b){return a.j.stop().then(function(){a.g=null;a.h=null;a.m=null;a.l=null;Fy(b,1)})})};var lz=function(a){return By(a.C,2,function(b){a.o.info("Suspending media streaming...");return a.j.stop().then(function(){a.o.info("Suspended media streaming.");Fy(b,3)})})};
kz.prototype.resume=function(){var a=this;return By(this.C,3,function(b){a.g&&"ended"==a.g.readyState&&(a.g=null);a.h&&"ended"==a.h.readyState&&(a.h=null);if(!a.g&&!a.h)return Promise.reject(Error("Cannot resume: All tracks have ended."));a.o.info("Resuming media streaming...");return a.j.start(a.g,a.h,a.l).then(function(){a.o.info("Resumed media streaming.");Fy(b,2)})})};var mz=function(a,b,c){this.C=a;this.l=b;this.j=c;this.o=db("mr.mirror.cast.WifiStatusMonitor");this.g=null;this.h=[]};mz.prototype.start=function(){var a=this;null==this.g&&(kb(this.o,"Starting Wifi Status Monitoring."),this.h=[],wy(this.j,"STATUS_RESPONSE",function(b){return nz(a,b)}),this.g=setInterval(function(){return oz(a)},12E4),oz(this))};mz.prototype.stop=function(){null!=this.g&&(kb(this.o,"Stopping Wifi Status Monitoring."),clearInterval(this.g),this.g=null,xy(this.j,"STATUS_RESPONSE"))};
var nz=function(a,b){if(null!=a.g)if(b.status){var c={};null!=b.status.g&&(c.wifiSnr=b.status.g);null!=b.status.h&&(c.wifiSpeed=b.status.h[3]);0==Object.keys(c).length?a.o.L(function(){return"No status fields populated in response: "+JSON.stringify(b)}):(c.timestamp=Date.now(),30==a.h.length&&a.h.shift(),a.h.push(c),a.o.info(function(){return"Current Wifi status: "+JSON.stringify(c)}))}else a.o.L(function(){return"Ignoring response without status: "+JSON.stringify(b)})},oz=function(a){a.j.sendMessage({type:"GET_STATUS",
sessionId:a.C,seqNum:qn(a.l),get_status:["wifiSnr","wifiSpeed"]})};var pz=function(a,b,c,d){this.H=b.Uh;this.K={extVersion:chrome.runtime.getManifest().version,extChannel:"public",mirrorSettings:yq(a),sender:navigator.userAgent||"UNKNOWN",receiverProductName:b.Se};this.G=c;this.D=d;this.l=this.h=this.s=this.m=this.C=this.u=this.j=null;this.g=[]};pz.prototype.hh=function(a){null!=this.h&&clearInterval(this.h);this.j=a;this.u=Date.now();this.h=setInterval(this.F.bind(this,a),9E5)};
pz.prototype.Yh=function(){null!=this.h&&(clearInterval(this.h),this.h=null);if(null!=this.j){var a=this.F(this.j);this.j=null;return a}return Promise.resolve()};pz.prototype.Jf=function(a,b){null==this.C&&(this.C=Date.now(),"function"===typeof a?this.m=a():"string"===typeof a&&(this.m=a),b&&"string"===typeof b.stack&&(this.s=b.stack))};
var rz=function(a,b){return(null==a.j?Promise.resolve():a.F(a.j)).then(function(){var c=b.map(function(d){d=qz(a,d);var e=d.map(function(g){return g.gd}).filter(function(g){return null!=g}),f=["["];d.map(function(g){return g.Fg}).forEach(function(g,h){0<h&&f.push(",");f.push(g)});f.push("]");return{gd:new Blob(e,{type:"application/gzip"}),Fg:new Blob(f,{type:"application/json"})}});a.g=[];return c})};
pz.prototype.F=function(a){var b=this;if(null!=this.l)return this.l;var c=zb(this.H).then(function(d){d={receiverVersion:d.g,receiverConnected:d.l,receiverOnEthernet:d.h,receiverHasUpdatePending:d.j,receiverUptimeSeconds:d.C};Object.assign(d,b.K);var e=Date.now();Object.assign(d,{startTime:b.u,endTime:e,activity:Ly(a),receiverWifiStatus:Array.from(b.D.h)});b.u=e;null!=b.C&&(Object.assign(d,{streamingErrorTime:b.C,streamingErrorMessage:b.m,streamingErrorCause:b.s}),b.C=null,b.m=null,b.s=null);return d});
return(this.l=Promise.all([c.then(function(d){return Ry(a,d)}),c,Sy(a)]).then(function(d){var e=n(d);d=e.next().value;var f=e.next().value;e=e.next().value;b.g.push({gd:d,Fg:new Blob([JSON.stringify(Object.assign({tags:f},e))],{type:"application/json"})});b.g=qz(b,b.G);b.l=null}))||Promise.resolve()};
var qz=function(a,b){b-=2;for(var c=[],d=a.g.length-1;0<=d;--d){b-=a.g[d].Fg.size+1;if(0>b)break;c.push({gd:null,Fg:a.g[d].Fg});if(null!=a.g[d].gd){var e=a.g[d].gd.size;b>=e&&(c[c.length-1].gd=a.g[d].gd,b-=e)}}return c.reverse()};var sz=function(a,b,c,d){d=void 0===d?null:d;Xj.call(this,b);var e=b.Cb;this.F=e.sessionId;this.H=a;this.V=d;this.o=db("mr.mirror.cast.Session");this.u=new zy;this.s=new pn("mirror.cast.SeqNumGenerator");this.m=new vy(b.id);this.C=new kz(e,this.H,this.s,this.m,this.V);this.l=null;this.g=new pz(a,e,c,new mz(this.F,this.s,this.m));this.D=null};t(sz,Xj);k=sz.prototype;
k.start=function(a){var b=this;return By(this.u,1,function(c){var d=Ux();return b.C.start(a,b).then(function(){b.C.j.G&&(b.g.D.start(),tz(b));d.end();b.D=Vx();Fy(c,2);return b})})};k.stop=function(){var a=this;return Dy(this.u,function(b){a.D&&(a.D.end(),a.D=null);a.g.D.stop();return a.C.stop().then(function(){return a.l?Yy(a.l):Promise.resolve()}).then(function(){a.l=null;Fy(b,4)})})};
k.sq=function(){var a=this,b={sessionId:this.F,seqNum:qn(this.s),type:"PRESENTATION",icons:[],title:Vj(this.Oc)};this.o.info("Sending session metadata update to receiver: "+this.F);this.m.sendMessage(b).catch(function(c){a.o.L("Failed to send activity to sink: "+c.message)})};k.hh=function(a){this.g.hh(a)};k.Yh=function(){return this.g.Yh()};k.Jf=function(a,b){this.g.Jf(a,b);this.o.error(a,b);this.stop()};
var uz=function(a,b){return rz(a.g,b)},tz=function(a){vz(a).then(function(b){(b.g||[]).includes("video")?wz(a,b):a.o.L(function(){return"Receiver incapable of Media Remoting: "+JSON.stringify(b)})}).catch(function(b){a.o.L("None/Invalid capabilites response. Media Remoting disabled.",b)})},vz=function(a){return new Promise(function(b,c){var d={type:"GET_CAPABILITIES",sessionId:a.F,seqNum:qn(a.s)};a.o.info(function(){return"Sending GET_CAPABILITIES message: "+JSON.stringify(d)});yy(a.m,d,"CAPABILITIES_RESPONSE",
3E4,function(e,f){if(null==e)return c(f),!0;if("ok"!=e.result||!e.capabilities)return c(Error("Bad response: "+JSON.stringify(e))),!0;if(e.h!=d.seqNum)return a.o.info(function(){return"Ignoring CAPABILITIES_RESPONSE with different seqNum: "+JSON.stringify(e)}),!1;kb(a.o,function(){return"Received CAPABILITIES_RESPONSE: "+JSON.stringify(e)});b(e.capabilities);return!0})})},wz=function(a,b){By(a.u,2,function(c){var d=a.h.Cb.Se||"<UNKNOWN>";if(!d.startsWith("Chromecast")&&!d.startsWith("Eureka Dongle"))return a.o.L('HACK: Media Remoting disabled because the receiver model--"'+
(d+'" according to discovery--is not a Chromecast.')),Fy(c),Promise.resolve();a.l=new Xy(a.h,b,a.H,a.s,a.m,a.V);return $y(a.l,a.N.bind(a),a).catch(function(e){a.o.error("Media Remoting start failed: "+e.message,e)}).then(function(){return Fy(c)})})};sz.prototype.N=function(){var a=this;return By(this.u,2,function(b){return new Promise(function(c,d){lz(a.C).then(function(){Fy(b,3);a.G=!0;Nj(a);c(a.X.bind(a))}).catch(function(e){a.Jf("Failed to suspend MediaStreamer before starting remoting",e);d(e)})})})};
sz.prototype.X=function(){var a=this;return By(this.u,3,function(b){return new Promise(function(c,d){a.C.resume().then(function(){Fy(b,2);a.G=!1;Nj(a);c()}).catch(function(e){a.Jf("Failed resume MediaStreamer after ending remoting mode",e);d(e)})})})};var xz=function(){Lj.call(this,"cast_streaming");this.m=this.F=this.K=this.H=this.l=null;this.ca=this.V="";this.ia=this.u=!1;this.ra=this.Fa.bind(this);this.N=this.X=this.Z=this.xb=this.C=null};t(xz,Lj);k=xz.prototype;k.jh=function(a){this.u=a||!1;this.ia=!0};k.getName=function(){return"cast_streaming"};
k.rl=function(a,b,c,d,e){var f=this;if(!this.u)return Lj.prototype.rl.call(this,a,b,c,d,e);this.M.info("Start mirroring on route "+a.id);if(!this.ia)return Zi(Error("Not initialized"));var g=new Promise(function(h,l){f.s().then(function(){if(Jj(b)&&c.shouldCaptureVideo)return qj(!1).then(function(q){f.ca=q})}).then(function(){return e?e(a).promise:a}).then(function(q){f.V=b;yz(f,q);var r=f.H.createInterfacePtrAndBind(),y=f.K.createInterfacePtrAndBind(),D=zz(q,c);Az(f,q,b,d);if(!f.l)throw new cj("Error to get mirroring service host");
f.F=new mojo.MirroringCastMessageChannelPtr;f.xb=Ux();f.l.start(D,r,y,mojo.makeRequest(f.F));f.C=new Xj(a,f.j.N.bind(f.j));Nj(f.C);Bz(f,q,b);f.X=function(){return h(q)};f.N=l}).catch(function(q){f.M.error("Mirroring launch error: "+q);f.Bg(void 0===q.reason?9:q.reason);l(q)})});return $i(g)};k.oi=function(a,b){return new sz(a,b,20969472,null)};k.Oh=function(){Wx(0)};k.Lh=function(){Wx(1)};k.kj=function(){Wx(2)};k.Mh=function(){Jb("MediaRouter.CastStreaming.Session.End")};
k.Bg=function(a){Kb("MediaRouter.CastStreaming.Start.Failure",a,bj)};k.Nh=function(){Jb("MediaRouter.CastStreaming.Stream.End")};
k.ak=function(a){var b=this;return this.u?Promise.resolve():(new Promise(function(c){return chrome.metricsPrivate.getIsCrashReportingEnabled(c)})).then(function(c){var d=c&&cy(),e=[9351424];d&&e.push(20969472);return uz(a,e).then(function(f){var g=f[f.length-1];f=om(f[0].gd).catch(function(h){b.M.error("Failed to persist events Blob.",h)});d&&0<g.gd.size?Zx(g.gd,void 0,b.Lx.bind(b)):c&&Yx("stats.json",g.Fg,void 0,void 0);return f})})};k.Lx=function(a){if(a){a=by();var b=Date.now();a.g=b}};
k.ql=function(a){if(this.u)return ab();this.M.info("Received message to upload logs for "+a);return this.g?uz(this.g,[20969472]).then(function(b){b=n(b).next().value;return 0==b.gd.size?"":Zx(b.gd,a)}):Promise.resolve(Cz(this,a))};
var Cz=function(a,b){var c=window.localStorage.getItem("mr.temp.mirror.cast.Service.eventsBlob");if(null==c||1>c.length)c=null;else{for(var d=new Uint16Array(c.length),e=0;e<c.length;++e)d[e]=c.charCodeAt(e);c=d.buffer;d=(new Uint8Array(c,c.byteLength-1,1))[0];c=new Uint8Array(c,0,c.byteLength-(0==d?2:1));c=new Blob([c],{type:"application/gzip"})}if(null!=c&&0!=c.size)return om(new Blob),a.M.info("Uploading saved logs for feedback."),Zx(c,b)};k=xz.prototype;
k.onError=function(a){this.N&&(this.N(a),this.X=this.N=null,this.Bg(9));this.M.info("Mirroring service error: "+a);this.s()};k.didStart=function(){this.X&&(this.X(),this.X=this.N=null);this.xb&&(this.xb.end(),this.xb=null);this.Z=Vx();Ij(this.V)?this.Oh():Jj(this.V)?this.Lh():Gj(this.V)&&this.kj()};k.didStop=function(){this.s()};k.send=function(a){if(this.m){var b=JSON.parse(a.jsonFormatData);kb(this.M,function(){return"Sending message: "+JSON.stringify(b)});this.m.sendMessage(a.jsonFormatData,{namespace:a.messageNamespace})}};
k.Mx=function(a){if(a&&(a.namespace_===mojo.MirroringWebRtcNamespace||a.namespace_===mojo.MirroringRemotingNamespace)&&this.F){var b=new mojo.MirroringCastMessage;b.messageNamespace=a.namespace_;"string"!==typeof a.data?this.M.info("Received non-string as JSON"):(b.jsonFormatData=a.data,this.F.send(b))}};
var yz=function(a,b){a.H=new mojo.Binding(mojo.MirroringSessionObserver,a,null);a.K=new mojo.Binding(mojo.MirroringCastMessageChannel,a,null);a.m=lw(b.id);a.m.onMessage=a.Mx.bind(a)},zz=function(a,b){var c=new mojo.MirroringSessionParameters;c.receiverAddress=new mojo.IPAddress;c.receiverAddress.addressBytes=a.Cb.Uh.split(".").map(function(d){return parseInt(d,10)});c.receiverModelName=a.Cb.Se;a=Dz(a.mediaSource);c.targetPlayoutDelay=Ez(a);!b.shouldCaptureVideo||!b.shouldCaptureAudio||a&&"0"===a.searchParams.get("streamingCaptureAudio")?
c.type=b.shouldCaptureVideo?mojo.MirroringSessionType.VIDEO_ONLY:mojo.MirroringSessionType.AUDIO_ONLY:c.type=mojo.MirroringSessionType.AUDIO_AND_VIDEO;return c},Ez=function(a){if(!a)return null;a=Number(a.searchParams.get("streamingTargetPlayoutDelayMillis"));return isNaN(a)||0>=a?null:new mojo.TimeDelta({microseconds:1E3*a})},Dz=function(a){if(!a)return null;try{return new URL(a)}catch(b){return null}},Az=function(a,b,c,d){a.l=new mojo.MirroringServiceHostPtr;b=b.Cb.tabId||-1;Ij(c)?a.j.getMirroringServiceHostForTab(b,
mojo.makeRequest(a.l)):Jj(c)?a.j.getMirroringServiceHostForDesktop(-1,a.ca,mojo.makeRequest(a.l)):Gj(c)?(b=new mojo.Url,b.url=c,a.j.getMirroringServiceHostForOffscreenTab(b,d||"",mojo.makeRequest(a.l))):a.l=null},Bz=function(a,b,c){Ij(c)&&!chrome.tabs.onUpdated.hasListener(a.ra)&&chrome.tabs.onUpdated.addListener(a.ra);(Ij(c)||Gj(c))&&Qj(a.C,b.Cb.tabId)};xz.prototype.Fa=function(a,b,c){Fj(14);this.C&&Sj(this.C,a,b,c)};
xz.prototype.s=function(){chrome.tabs.onUpdated.removeListener(this.ra);return this.u?this.ia?this.l?(this.l.ptr.reset(),this.F=this.l=null,this.m&&this.m.dispose(),this.m=null,this.H&&(this.H.close(),this.H=null),this.K&&(this.K.close(),this.K=null),Rj(this.j,this.C.h.id),this.C=null,this.ca=this.V="",this.Z&&(this.Z.end(),this.Z=null),this.Mh(),Promise.resolve(!0)):Promise.resolve(!1):Promise.reject("Not initialized"):Lj.prototype.s.call(this)};
xz.prototype.oa=function(a,b,c,d,e,f){return this.u?Zi(Error("Mirroring service does not support updating stream")):Lj.prototype.oa.call(this,a,b,c,d,e,f)};xz.prototype.send=xz.prototype.send;xz.prototype.didStop=xz.prototype.didStop;xz.prototype.didStart=xz.prototype.didStart;xz.prototype.onError=xz.prototype.onError;var Fz=new xz;Cj("mr.mirror.cast.Service",Fz);
