// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1613888309);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1613888278);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 104);
user_pref("browser.newtabpage.activity-stream.impressionId", "{2f8411ce-ab94-437a-bfa1-26261820958c}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1613888303802");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1613890073802");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1613888295658");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1613909895658");
user_pref("browser.search.region", "ID");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1613888285");
user_pref("browser.slowStartup.averageTime", 3291);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20210105180113");
user_pref("browser.startup.homepage_override.mstone", "84.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1613888281);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1613888289709");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "84.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "0e1506f08fea486ca96921e91738b60f");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "84.0.2");
user_pref("extensions.lastPlatformVersion", "84.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_picture_in_picture_overrides", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"8f0ea13f-bb3f-4e78-8a10-4eb226af7b1d\",\"formautofill@mozilla.org\":\"6b4dbfe6-c090-4beb-92dd-ca14b16f60f0\",\"screenshots@mozilla.org\":\"4f51006a-d8af-4756-bcdf-5ddc5c0fbcd7\",\"webcompat-reporter@mozilla.org\":\"722efe0b-7292-48b4-a9f7-4941505d8765\",\"webcompat@mozilla.org\":\"2cff2514-a694-4e70-8a41-81ac943dd2a7\",\"default-theme@mozilla.org\":\"222d8967-e218-4b82-99fc-2d7df76b6983\",\"google@search.mozilla.org\":\"38334e0b-b8c2-4f47-b272-d53d6bb24826\",\"amazondotcom@search.mozilla.org\":\"279ada42-2ab1-4adb-b062-d423ad8a775d\",\"wikipedia@search.mozilla.org\":\"ae1958a2-5102-4c33-80e9-374c20d88e9e\",\"bing@search.mozilla.org\":\"b8802079-9531-4906-8609-c2066aae6d79\",\"ddg@search.mozilla.org\":\"2430cae1-1aba-4017-ba89-bcee830610ba\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "54ce856f-4e91-4100-89df-73999512fb95");
user_pref("security.sandbox.plugin.tempDirSuffix", "e0a4f8b6-0ff9-4458-a2e7-595c29d78271");
user_pref("toolkit.startup.last_success", 1613888278);
user_pref("toolkit.telemetry.cachedClientID", "2afad800-1f64-453e-9766-b6e07199bade");
user_pref("toolkit.telemetry.previousBuildID", "20210105180113");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
